geonode_mapstore_client/client/js/plugins.js
geonode_mapstore_client/static/geonode/js/ms2/utils/ms2_composer_plugins.js
geonode_mapstore_client/static/geonode/js/ms2/utils/ms2_map_embed_plugins.js
geonode_mapstore_client/static/geonode/js/ms2/utils/ms2_map_viewer_plugins.js

Closes #21

---

geonode_mapstore_client/client/js/plugins.js
geonode_mapstore_client/client/themes/default/less/geonode.less
geonode_mapstore_client/static/geonode/js/ms2/utils/ms2_base_plugins.js
geonode_mapstore_client/static/geonode/js/ms2/utils/ms2_composer_plugins.js
geonode_mapstore_client/static/geonode/js/ms2/utils/ms2_map_viewer_plugins.js

This PR: 
- Updates the Plugins and the configurations to enable TOC tools
- Removes permissions from save dialog

Update 2020.02 fixes

---

geonode_mapstore_client/client/themes/default/less/geonode.less

This uses the autofit modal functionality instead of setting the modal style from  theme

fixed style of dialogs

---

geonode_mapstore_client/static/geonode/js/ms2/utils/ms2_map_viewer_plugins.js
geonode_mapstore_client/static/geonode/js/ms2/utils/ms2_viewer_plugins.js

[Backport 2.1.x] Remove the geocoding configuration from Mapstore client

---

mapstore2_adapter/plugins/serializers.py

Remove race hazard when uploading a thumbnail on map's creation

[Fixes #90] Uploaded thumbnail race hazard

---

geonode_mapstore_client/templates/geonode-mapstore-client/app_list.html

Hides `Create New Apps` button From anonymous users

[Fixes #141] Create New Apps button is enabled for Anonymous users

---

geonode_mapstore_client/templates/geonode-mapstore-client/app_list.html

Hides `Create New Apps` button From anonymous users

[Backport 2.1.x] #141: Create New Apps button is enabled for Anonymous users

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/components/Menu/DropdownList.jsx
geonode_mapstore_client/client/js/components/Menu/Menu.js
geonode_mapstore_client/client/js/components/Menu/MenuItem.js
geonode_mapstore_client/client/js/components/home/BrandNavbar.jsx
geonode_mapstore_client/client/js/components/home/FiltersMenu.jsx
geonode_mapstore_client/client/js/components/theme/RootStyle.jsx
geonode_mapstore_client/client/js/epics/gnsearch.js
geonode_mapstore_client/client/js/reducers/gnsearch.js
geonode_mapstore_client/client/js/routes/Home.jsx
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/scss/_filter-menu.scss
geonode_mapstore_client/client/themes/geonode/scss/_variables.scss
geonode_mapstore_client/client/themes/geonode/scss/geonode.scss

This PR improve the UI of the current filter toggle button and add a clear filter button to have a quick access to this functionality

Improve filter form toggle UI of search and homepage

---

geonode_mapstore_client/client/js/routes/Home.jsx
geonode_mapstore_client/client/themes/geonode/scss/_brand-navbar.scss
geonode_mapstore_client/client/themes/geonode/scss/_footer.scss
geonode_mapstore_client/client/themes/geonode/scss/_menu-index.scss

This PR changes the navbar styles and it makes them full width.

Client - Brand navbar, action navbar and footer to full width

---

geonode_mapstore_client/client/js/apps/gn-geostory.js
geonode_mapstore_client/client/js/apps/gn-home.jsx
geonode_mapstore_client/client/js/apps/gn-map.js
geonode_mapstore_client/client/js/plugins/SaveAs.jsx
geonode_mapstore_client/client/package.json

Add Permission Check when adding a resource
- Hides the save as button if user doesn't have permissions to add resource
#145

145: Add check for resource permission

---

geonode_mapstore_client/client/themes/geonode/scss/_hero.scss

- add centering for hero content

Center Hero Content

---

geonode_mapstore_client/client/themes/geonode/scss/_variables.scss

- Change Background for hero component to #0c3756

Update background color for hero component

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js

Exclude metadata_only results from resources request such as service type

Exclude metadata_only results from resources request

---

geonode_mapstore_client/templates/geonode-mapstore-client/app/geostory.html
geonode_mapstore_client/templates/geonode-mapstore-client/layer_embed.html
geonode_mapstore_client/templates/geonode-mapstore-client/map_edit.html
geonode_mapstore_client/templates/geonode-mapstore-client/map_embed.html
geonode_mapstore_client/templates/geonode-mapstore-client/viewer.html
geonode_mapstore_client/templates/index.html
geonode_mapstore_client/templatetags/client_version.py

[Fixes #189]: A hash is needed for gn-xxx.js links otherwise browsers load stale code

---

mapstore2_adapter/geoapps/geostories/api/serializers.py

[Fixes #204]: Ceating a New GeoStory Displays a Network Error

---

mapstore2_adapter/geoapps/geostories/api/serializers.py

[Backport 2.1.x][Fixes #204]: Ceating a New GeoStory Displays a Network Error 

---

mapstore2_adapter/plugins/geonode.py

This PR completes the one on geonode https://github.com/GeoNode/geonode/pull/7624

Set default tile size for WMS layers in map configurations

---

geonode_mapstore_client/client/themes/default/less/geonode.less

Fix Icons not visible on Empty GeoStory

218: Add toolbar icons are not visible when a GeoStory is empty 

---

geonode_mapstore_client/client/js/utils/MenuUtils.js
geonode_mapstore_client/client/js/utils/__tests__/MenuUtils-test.js

Adds Check for if perms are undefined to prevent app from crushing

check for perms undefined

---

geonode_mapstore_client/client/js/epics/gnviewer.js
geonode_mapstore_client/client/js/plugins/ActionNavbar.jsx
geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
geonode_mapstore_client/client/js/plugins/Save.jsx
geonode_mapstore_client/client/js/plugins/SaveAs.jsx
geonode_mapstore_client/client/js/plugins/Share.jsx
geonode_mapstore_client/client/js/plugins/ViewerLayout.jsx
geonode_mapstore_client/client/js/plugins/actionnavbar/buttons.jsx
geonode_mapstore_client/client/js/plugins/index.js
geonode_mapstore_client/client/js/selectors/gnresource.js
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/less/_bootstrap-variables.less
geonode_mapstore_client/client/themes/geonode/less/geonode-legacy.less
geonode_mapstore_client/client/themes/geonode/less/geonode.less
geonode_mapstore_client/client/themes/geonode/less/ms-theme.less

Fixes structure of viewer and workflow of saving existing GeoStory and Map

Improve structure of viewers

---

geonode_mapstore_client/client/js/components/home/FeaturedList.jsx

- Stop making request when page size is NAN

Client - Error on featured resources request

---

geonode_mapstore_client/client/js/components/RootStyle/RootStyle.jsx
geonode_mapstore_client/client/js/components/home/LanguageSelector.jsx
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/themes/geonode/less/_bootstrap-variables.less

The primary buttons were not correctly displayed with custom styles. This PR fixes the script that compute the buttons style and adds a border-radius equal to 2px

Fix style for menu buttons

---

geonode_mapstore_client/client/js/components/home/DetailsPanel.jsx
geonode_mapstore_client/client/js/plugins/DetailViewer.jsx

Client - add flag to button detail in navbar and rm link resource in viewer 
result in PR:

Client - add flag to button detail in navbar and rm link resource in viewer 

---

geonode_mapstore_client/client/js/actions/gnresource.js
geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/components/Menu/MenuItem.js
geonode_mapstore_client/client/js/components/home/DetailsPanel.jsx
geonode_mapstore_client/client/js/epics/gnsave.js
geonode_mapstore_client/client/js/epics/gnviewer.js
geonode_mapstore_client/client/js/routes/Home.jsx
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

- fix footer style
- use OGC link to configure layer in viewer
- rename favourite to favorite

Editors should use the new link properties returned by API v2

---

geonode_mapstore_client/client/js/components/home/DetailsPanel.jsx

Download button inside documents editor
https://user-images.githubusercontent.com/4085786/123994297-881c2100-d9cd-11eb-9d32-597546aa9604.mov

Download button inside documents editor

---

geonode_mapstore_client/client/themes/geonode/less/_details-panel.less

detail panel alignments regression

detail panel alignments regression 

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js

Missing count for filter values
Result in PR:
https://user-images.githubusercontent.com/4085786/124241785-5ebddb00-db1c-11eb-9863-95a7c9e7262a.mov

Missing count for filter values

---

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/themes/geonode/less/_action-navbar.less

Add separator between datasets, docs and the rest of the presentational resources

Add separator between datasets, docs and the rest of the presentational resources

---

geonode_mapstore_client/client/js/epics/gnviewer.js
geonode_mapstore_client/client/js/plugins/actionnavbar/buttons.jsx
geonode_mapstore_client/client/js/plugins/index.js
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

Export button inside dataset editor
Result in PR:
https://user-images.githubusercontent.com/4085786/124142978-02f74180-da8b-11eb-9cfc-36220d7f2cd6.mov

Export button inside dataset editor

---

geonode_mapstore_client/client/js/plugins/DetailViewer.jsx

Add favorites icon to detail panel
Result in PR:
https://user-images.githubusercontent.com/4085786/124259045-5f5f6d00-db2e-11eb-9290-e5469379fb21.mov

Add favorites icon to detail panel 

---

geonode_mapstore_client/client/js/components/FiltersForm/FiltersForm.jsx

This PR fix:
- Extent filter doesn't trigger filter requests
https://user-images.githubusercontent.com/4085786/124624363-1a646f00-de7d-11eb-933f-37642861299d.mov
- Clear filters apply again previous filters

Extent filter doesn't trigger filter requests

---

geonode_mapstore_client/client/js/components/home/BrandNavbar.jsx
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

Fill "next" parameter with the current page on login
Result in PR:
https://user-images.githubusercontent.com/4085786/124774547-311eca80-df3e-11eb-895e-d9616cf56c30.mov

Fill "next" parameter with the current page on login

---

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

Editor menus aren't respecting permissions

Editor menus aren't respecting permissions

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/epics/gnsave.js
geonode_mapstore_client/client/js/epics/gnviewer.js

It will be used to save changes inside the Details panel (thumbnail, title and abstract)
Result in PR:
https://user-images.githubusercontent.com/4085786/125794318-c708f483-3ac3-49ee-b3ea-c03d9144ee32.mov

Add Save button to Dataset editor

---

geonode_mapstore_client/client/js/components/DefinitionList/DefinitionList.jsx
geonode_mapstore_client/client/js/components/DefinitionList/__test__/DefinitionList-test.jsx
geonode_mapstore_client/client/js/components/DefinitionList/index.js
geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
geonode_mapstore_client/client/js/components/Tabs/Tabs.jsx
geonode_mapstore_client/client/js/components/Tabs/__test__/Tabs-test.jsx
geonode_mapstore_client/client/js/components/Tabs/index.js
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/less/_details-panel.less

Result in PR:
https://user-images.githubusercontent.com/4085786/126285603-4a802677-03f1-4ee7-9471-0a3c3ba78168.mov

311 info tab

---

geonode_mapstore_client/client/js/plugins/ActionNavbar.jsx
geonode_mapstore_client/client/js/selectors/gnresource.js

Result PR:
https://user-images.githubusercontent.com/4085786/126466624-79ce99c5-7cac-4c3e-98e3-efa1e6a59857.mov

Enable Save and Save As button in create new Map Or Geostory

---

geonode_mapstore_client/client/js/components/DefinitionList/DefinitionList.jsx
geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
geonode_mapstore_client/client/themes/geonode/less/_details-panel.less

Show only resource type in field tab, some tabs improvements
Result in PR:

Show only resource type in field tab, some tabs improvements

---

geonode_mapstore_client/templates/geonode-mapstore-client/snippets/brand_navbar.html
geonode_mapstore_client/templates/geonode-mapstore-client/snippets/menu_item.html

[Fixes #375] Fill "next" parameter with the current page on login

---

geonode_mapstore_client/client/js/components/CardGrid/CardGrid.jsx

Remove card menu
Result in PR:
https://user-images.githubusercontent.com/4085786/126770300-e492472d-a03f-4a0e-b8e7-693df5da7244.mov

Remove card menu

---

geonode_mapstore_client/templates/geonode-mapstore-client/snippets/search_bar.html

[Fixes #378] Wrong encoding of result from search autocomplete

---

geonode_mapstore_client/apps.py

Rename reference to MapstoreClient

[Fixes #7921] Rename reference to MapstoreClient

---

geonode_mapstore_client/client/js/components/ContentsEditable/TextEditable.jsx
geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
geonode_mapstore_client/client/themes/geonode/less/_variables.less

Remove edit icons from detail panel 
https://user-images.githubusercontent.com/4085786/128896554-b9d97a16-03b3-496b-9001-850be150a1fc.mov

Remove edit icons from detail panel 

---

geonode_mapstore_client/client/js/components/FeaturedList/FeaturedList.jsx
geonode_mapstore_client/client/themes/geonode/less/_card-grid.less

Decrease size of featured resource pagination

---

geonode_mapstore_client/client/js/apps/gn-map.js
geonode_mapstore_client/client/js/epics/gnresource.js
geonode_mapstore_client/client/js/epics/gnsave.js
geonode_mapstore_client/client/js/plugins/SaveAs.jsx
geonode_mapstore_client/client/js/plugins/Share.jsx
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/themes/geonode/less/_main-event.less
geonode_mapstore_client/client/themes/geonode/less/ms-theme.less
geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html
geonode_mapstore_client/templates/geonode-mapstore-client/dataset_embed.html
geonode_mapstore_client/templates/geonode-mapstore-client/map_embed.html

- remove of old configuration from localConfig.json
- update dataset and map embed template to use the same requests and styles of others new template
- descrease size of buttons in map viewer to use one theme for preview and embed

Clean up configuration and update map/dataset embed templates

---

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx
geonode_mapstore_client/client/js/components/ResourceStatus/ResourceStatus.jsx
geonode_mapstore_client/client/js/components/ResourceStatus/index.js
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/less/_card-grid.less
geonode_mapstore_client/client/themes/geonode/less/_details-panel.less

Add "under approval" and "unpublished" labels
Result in PR:

Add "under approval" and "unpublished" labels

---

geonode_mapstore_client/client/js/components/Menu/DropdownList.jsx
geonode_mapstore_client/client/js/components/Menu/MenuItem.js
geonode_mapstore_client/client/js/epics/__tests__/gnsave-test.js
geonode_mapstore_client/client/js/epics/gnresource.js
geonode_mapstore_client/client/js/epics/gnsave.js
geonode_mapstore_client/client/js/plugins/ActionNavbar.jsx
geonode_mapstore_client/client/js/plugins/Save.jsx
geonode_mapstore_client/client/js/reducers/__tests__/gnresource-test.js
geonode_mapstore_client/client/js/reducers/gnresource.js
geonode_mapstore_client/client/js/reducers/resourceservice.js
geonode_mapstore_client/client/js/selectors/resource.js
geonode_mapstore_client/client/js/utils/LocalStorageUtils.js
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/less/_base.less

This PR introduces controls to alert the user that there are pending changes in the current vierwer/editor. This implementation uses the browser native `window.confirm` and `beforeunload` event the allows to intercept event outtside of the current app

Notify user when editor has pending changes

---

README.md

update readme file with, update plugin configuration example

[Documentation] update plugin configuration

---

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

enable fullscreen for dashboard

enable fullscreen for dashboard

---

geonode_mapstore_client/client/js/plugins/DownloadResource.jsx
geonode_mapstore_client/client/js/plugins/index.js
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

Configure a link in the ActionNavbar of documents page targeting the downloadable resource

Client - Download link for documents page 

---

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/templates/geonode-mapstore-client/layer_export.html
geonode_mapstore_client/templates/geonode-mapstore-client/map_edit.html

This PR introduce an  automatic opening of the export window from request parameters

Enable the automatic opening of the export window from request parameters

---

geonode_mapstore_client/client/js/epics/favorite.js

This PR introduce, the update filtered list by favrorites if a resource is unmarked as favorite from the preview panel
https://user-images.githubusercontent.com/4085786/132014763-c8e141d4-d404-4a47-9c2e-ca294dd753dd.mov

303 update filtered list

---

geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/less/_menu.less
geonode_mapstore_client/client/themes/geonode/less/_variables.less

This PR introduces some improvement for filter notification in homepage

Filters notification improvement

---

geonode_mapstore_client/client/themes/geonode/less/geonode-legacy.less

This PR fixes the b
roken user card inside legacy People page

Broken user card inside legacy People page

---

geonode_mapstore_client/templates/geonode-mapstore-client/snippets/brand_navbar.html

[Fixes #464] Wrong Sign in Redirect

---

geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json

This PR Rename the label of the "Details" button inside the action bar to "Info"

Rename "Details" to "Info" 

---

geonode_mapstore_client/client/js/components/ContentsEditable/TextEditable.jsx
geonode_mapstore_client/client/js/epics/favorite.js

This PR fix :
the update of favorites list, when the item is added or removed  favorite, clicking on icon star nel preview panel

Removing a favorite doesn't update the favorites list and the resource cannot be set as favorite again

---

geonode_mapstore_client/client/themes/geonode/less/_share.less

This PR fixes, the bugs about select options
result:

Assorted issues for the share plugin 

---

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
geonode_mapstore_client/client/js/components/Permissions/Permissions.jsx

This PR introduces the owner link, in the top of permissions list

Add owner in permissions list

---

geonode_mapstore_client/client/js/hooks/useLazyPlugins.js
geonode_mapstore_client/client/js/hooks/usePluginItems.js
geonode_mapstore_client/client/js/plugins/index.js
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/package.json
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

This PR fixes a wrong behaviour on the loading phase of plugin and it fixes also some issues with action navbar menus

Restore missing print menu item

---

geonode_mapstore_client/client/themes/geonode/less/_menu.less

This PR introduces the background transparent for Sign In and Register button

Make Sign In and Register button background transparent

---

geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/themes/geonode/less/_resource-card.less

This PR introduces: View button to be in reach also in list view

Add "View" button to cards in list view

---

geonode_mapstore_client/apps.py

References: #561
References: https://github.com/GeoNode/geonode/issues/8300

[Closes #561] Hide "download" permissions for maps and apps

---

.gitmodules

This PR: Alignment of submodules target branch which should follow Mapstore2 committed branch

Align Mapstore2 3.2.x submodules

---

.gitmodules

This PR: Alignment of submodules target branch which should follow Mapstore2 committed branch

 Align Mapstore2 3.3.x submodules

---

.gitmodules

This PR: Alignment of submodules target branch which should follow Mapstore2 committed branch

 Align Mapstore2 master branch submodules

---

mapstore2_adapter/plugins/geonode.py

Add dynamic layer from GET request to an existing map config

---

geonode_mapstore_client/client/devServer.js
geonode_mapstore_client/client/js/components/Permissions/Permissions.jsx
geonode_mapstore_client/client/js/utils/AppUtils.js

The users list was wrongly positioned in the share plugin. This PR correctly places the users list where they belong

Wrong positioning of users list inside share plugin

---

geonode_mapstore_client/client/.gitignore
geonode_mapstore_client/client/README.md
geonode_mapstore_client/client/devServer.js
geonode_mapstore_client/client/js/actions/gnresource.js
geonode_mapstore_client/client/js/actions/gnsave.js
geonode_mapstore_client/client/js/actions/gnsearch.js
geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/components/Menu/Menu.js
geonode_mapstore_client/client/js/epics/index.js
geonode_mapstore_client/client/js/plugins/Save.jsx
geonode_mapstore_client/client/js/plugins/SaveAs.jsx
geonode_mapstore_client/client/js/plugins/actionnavbar/buttons.jsx
geonode_mapstore_client/client/js/selectors/config.js
geonode_mapstore_client/client/js/utils/APIUtils.js
geonode_mapstore_client/client/js/utils/CoordinatesUtils.js
geonode_mapstore_client/client/js/utils/FileUtils.js
geonode_mapstore_client/client/js/utils/MenuUtils.js
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/package.json

base configuration to start to fix documentation using jsdoc

Add base docs files and config

---

geonode_mapstore_client/client/themes/geonode/less/_menu.less
geonode_mapstore_client/client/themes/geonode/less/_variables.less

This PR introduces: more relevance to actionbar buttons

Give more relevance to ationbar buttons

---

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

This PR changes the check to create the map in dataset, checking the user perms

Create map from dataset should be available if the user has add permission and access to the resource

---

geonode_mapstore_client/client/js/plugins/SaveAs.jsx
geonode_mapstore_client/client/js/plugins/save/SaveModal.jsx

This PR Remove the thumbnail input field from the Save As plugin

Remove the thumbnail input field from the Save As plugin

---

geonode_mapstore_client/client/js/plugins/Legend.jsx
geonode_mapstore_client/client/js/plugins/__tests__/legend-test.jsx
geonode_mapstore_client/client/js/plugins/index.js
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/themes/geonode/less/_legend.less
geonode_mapstore_client/client/themes/geonode/less/geonode.less

This PR introduces a plugin that shows the layer legends in the top left corner of dataset page.

Add Legend plugin to dataset page

---

geonode_mapstore_client/client/js/components/ALink/ALink.jsx
geonode_mapstore_client/client/js/components/ALink/index.js
geonode_mapstore_client/client/js/components/AuthorInfo/AuthorInfo.jsx
geonode_mapstore_client/client/js/components/AuthorInfo/index.js
geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx
geonode_mapstore_client/client/js/components/__tests__/ALink-test.jsx
geonode_mapstore_client/client/js/components/__tests__/AuthorInfo-test.jsx
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
geonode_mapstore_client/client/themes/geonode/less/_resource-card.less

This PR provides an improvement to the `<ResourceCard />` and `<DetailsPanel />`UI. 
Action buttons and author information are now footers in the cards and info about resource type is available in the preview panel.

 UI improvements to cards and preview panel

---

geonode_mapstore_client/client/js/components/ALink/ALink.jsx
geonode_mapstore_client/client/js/components/FeaturedList/FeaturedList.jsx
geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx
geonode_mapstore_client/client/themes/geonode/less/_resource-card.less

Featured resources now have bold titles.

Make cards title of featured content bold

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/components/ALink/ALink.jsx
geonode_mapstore_client/client/js/components/AuthorInfo/AuthorInfo.jsx
geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx
geonode_mapstore_client/client/js/epics/gnresource.js
geonode_mapstore_client/client/js/epics/gnsave.js
geonode_mapstore_client/client/js/epics/index.js
geonode_mapstore_client/client/js/plugins/DatasetsCatalog.jsx
geonode_mapstore_client/client/js/plugins/index.js
geonode_mapstore_client/client/js/selectors/resource.js
geonode_mapstore_client/client/js/utils/CoordinatesUtils.js
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/js/utils/__tests__/CoordinatesUtils-test.js
geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/less/_card-grid.less
geonode_mapstore_client/client/themes/geonode/less/_datasets-catalog.less
geonode_mapstore_client/client/themes/geonode/less/_resource-card.less
geonode_mapstore_client/client/themes/geonode/less/geonode.less

- dataset catalog plugin that uses the V2 API to map GeoNode resource to layer
- improve map workflow based on latest changes on V2 API

Client - GeoNode Datasets Catalog Plugin

---

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json

This PR add a new "unpublished" in the filters form

502 unpublished filter option

---

geonode_mapstore_client/client/js/plugins/DatasetsCatalog.jsx

This PR fixes the pushing the list to top when scrolling with mouse wheel
https://user-images.githubusercontent.com/4085786/144404397-3b8609b1-7117-4cc7-bdc2-c0699b960f7b.mov

New catalog keeps pushing the list to top when scrolling with mouse wheel

---

geonode_mapstore_client/client/js/components/ActionNavbar/ActionNavbar.jsx
geonode_mapstore_client/client/themes/geonode/less/_menu.less

- The font of the resource title is reduced
- breadcrumb width is increased
- info icon is placed on the right end inside breadcrumb

Style Adjustments to breadcrumb

---

geonode_mapstore_client/client/js/epics/index.js
geonode_mapstore_client/client/js/epics/visualstyleeditor.js
geonode_mapstore_client/client/js/plugins/DatasetsCatalog.jsx
geonode_mapstore_client/client/js/plugins/VisualStyleEditor.jsx
geonode_mapstore_client/client/js/plugins/layersettings/WMSLayerSettings.jsx
geonode_mapstore_client/client/js/selectors/resource.js
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/less/_layer-settings.less
geonode_mapstore_client/client/themes/geonode/less/_visual-style-editor.less
geonode_mapstore_client/client/themes/geonode/less/ms-theme.less

This is the inital implementation of the Visual Style Editor in the map viewer.

Add visual style editor for map viewer

---

geonode_mapstore_client/client/js/components/ActionButtons/ActionButtons.jsx
geonode_mapstore_client/client/js/components/ActionButtons/index.js
geonode_mapstore_client/client/js/components/CardGrid/CardGrid.jsx
geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx
geonode_mapstore_client/client/js/components/__tests__/ALink-test.jsx
geonode_mapstore_client/client/js/components/__tests__/ActionButtons-test.jsx
geonode_mapstore_client/client/js/components/__tests__/AuthorInfo-test.jsx
geonode_mapstore_client/client/themes/geonode/less/_resource-card.less

In this PR, the ellipsis action button on resource cards have been repositioned and made to appear on hover.

Card actions on hover

---

geonode_mapstore_client/client/js/observables/persistence/index.js
geonode_mapstore_client/client/js/utils/ResourceUtils.js

This fix also the map creation function

Add pk reference inside dashboard map

---

geonode_mapstore_client/client/js/components/CardGrid/CardGrid.jsx
geonode_mapstore_client/client/js/components/FeaturedList/FeaturedList.jsx
geonode_mapstore_client/client/js/routes/Home.jsx
geonode_mapstore_client/client/js/routes/catalogue/ConnectedCardGrid.jsx
geonode_mapstore_client/client/js/utils/ResourceServiceUtils.js

In this PR, menu on hover has been added on featured cards.

Menu on hover doesn't appear on featured content cards

---

geonode_mapstore_client/client/js/components/Menu/DropdownList.jsx

The sub menu for save button has been included in burger menu (for mobile devices)

Save button is cut when viewed on mobile devices

---

geonode_mapstore_client/client/js/epics/visualstyleeditor.js
geonode_mapstore_client/client/js/plugins/LayerSettings.jsx
geonode_mapstore_client/client/js/plugins/VisualStyleEditor.jsx
geonode_mapstore_client/client/js/plugins/layersettings/GeoNodeStyleSelector.jsx
geonode_mapstore_client/client/js/plugins/layersettings/WMSLayerSettings.jsx
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js

The edit style button will be visible for the map layer style in the list of available styles

Add edit button to list of styles

---

geonode_mapstore_client/apps.py
geonode_mapstore_client/client/js/apps/gn-map.js
geonode_mapstore_client/client/js/utils/AppUtils.js
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
geonode_mapstore_client/context_processors.py
geonode_mapstore_client/hooksets.py
geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html

This PR removes all variables not used anymore and introduces all the settings needed to setup layers and maps pages

#678: Review _geonode_config.html variables

---

geonode_mapstore_client/client/js/epics/gnsave.js

Restored previous behaviour to save thembnail

Geostory and Dashboard thumbnail set from info panel are not sent to the backend

---

geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/less/_card-grid.less
geonode_mapstore_client/client/themes/geonode/less/_menu.less

This PR expands the spacing between Featured items and items list, changes 'Create new' button text to 'Add resource' and increases the size of the button to make it stand out. Below is the result:

Expand area between featured content and items list and give more relevance to the "add content" action button

---

geonode_mapstore_client/client/js/epics/visualstyleeditor.js
geonode_mapstore_client/client/js/plugins/visualstyleeditor/TemplateSelector.jsx
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
geonode_mapstore_client/client/themes/geonode/less/_visual-style-editor.less

Layers in map was not using the correct default style

Fix map style creation workflow

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js

remove timeout from create map request

#694: Error when saving a new map 

---

README.md
docs/client.md
geonode_mapstore_client/client/README.hbs
geonode_mapstore_client/client/js/epics/visualstyleeditor.js
geonode_mapstore_client/client/package.json

This PR adds a script to convert all the jsdocs from the source code of the client to a markdown

Update client documentation

---

geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx

This PR introduces a variant change from default to primary for filters button

Replace filters icon with a primary button

---

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

`<ActionNavbar />` menu has been reordered

Reorder actionbar menu items

---

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/less/_details-panel.less

This PR introduces style adjustments in `DetailsPanel` texts

Info Panel layout enhancements

---

mapstore2_adapter/plugins/geonode.py

[Fixes #711] Always generate feature template from updated layer attributes

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/apps/gn-catalogue.js
geonode_mapstore_client/client/js/epics/gnsync.js
geonode_mapstore_client/client/js/routes/UploadDataset.jsx
geonode_mapstore_client/client/themes/geonode/less/_main-event.less
geonode_mapstore_client/client/themes/geonode/less/_upload.less
geonode_mapstore_client/client/themes/geonode/less/geonode.less
geonode_mapstore_client/context_processors.py
geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html

This PR includes a new page for dataset upload. It's a work in progress and accessible at /catalogue/#/upload/dataset.

Add new updload dataset page

---

geonode_mapstore_client/client/js/components/ResourceStatus/ResourceStatus.jsx
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/less/_card-grid.less
geonode_mapstore_client/client/themes/geonode/less/_details-panel.less

This PR changes labels for 'UNPUBLISHED' and 'NOT APPROVED' resources as seen below

Change labels for not published and not approved resources

---

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
geonode_mapstore_client/client/js/plugins/Share.jsx
geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
geonode_mapstore_client/client/themes/geonode/less/_share.less
geonode_mapstore_client/client/themes/geonode/less/ms-theme.less

Align styles of close buttons:
- dialog
- panel

Harmonize close buttons for the various panels

---

geonode_mapstore_client/client/themes/geonode/less/_details-panel.less

Updated styles for resource thumbnails for consistency

Improve icon buttons for setting resource thumbnail

---

geonode_mapstore_client/client/js/routes/UploadDataset.jsx

[Fixes #729] Update supportedDatasetTypes

---

geonode_mapstore_client/client/js/apps/gn-document.js
geonode_mapstore_client/templates/documents/document_embed.html
geonode_mapstore_client/templates/geonode-mapstore-client/dataset_embed.html

Add a new app to use for embedded documents

Add embed template for documents

---

geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx
geonode_mapstore_client/client/js/components/MediaViewer/Scene3DViewer.jsx
geonode_mapstore_client/client/js/components/MediaViewer/__tests__/Media-test.jsx
geonode_mapstore_client/client/js/utils/FileUtils.js
geonode_mapstore_client/client/package.json
geonode_mapstore_client/client/themes/geonode/less/_media-viewer.less

A viewer to visualize document file of types glb, gltf and pcd in a 3D scene

Add scene 3d viewer for documents glb, gltf and pcd

---

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
geonode_mapstore_client/client/js/components/Permissions/GeoLimits.jsx
geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
geonode_mapstore_client/client/js/utils/CoordinatesUtils.js
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/js/utils/__tests__/CoordinatesUtils-test.js
geonode_mapstore_client/client/themes/geonode/less/_details-panel.less

Map thumbnail has been modified for consistency

Fix set thumbnail map widget

---

geonode_mapstore_client/client/js/routes/UploadDataset.jsx
geonode_mapstore_client/client/js/routes/UploadDocument.jsx
geonode_mapstore_client/client/js/routes/upload/PendingUploadCard.jsx
geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
geonode_mapstore_client/client/js/routes/upload/UploadContainer.jsx
geonode_mapstore_client/client/js/routes/upload/UploadListContainer.jsx
geonode_mapstore_client/client/js/utils/AppUtils.js
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fi-FI.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.hr-HR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/static/mapstore/translations/data.nl-NL.json
geonode_mapstore_client/client/static/mapstore/translations/data.pt-PT.json
geonode_mapstore_client/client/static/mapstore/translations/data.sk-SK.json
geonode_mapstore_client/client/static/mapstore/translations/data.sv-SE.json
geonode_mapstore_client/client/static/mapstore/translations/data.vi-VN.json
geonode_mapstore_client/client/static/mapstore/translations/data.zh-ZH.json
geonode_mapstore_client/client/themes/geonode/less/_upload.less

Update upload pages ui

---

geonode_mapstore_client/client/js/actions/gnresource.js
geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
geonode_mapstore_client/client/js/components/FiltersForm/FilterByExtent.jsx
geonode_mapstore_client/client/js/components/ZoomTo/ZoomTo.jsx
geonode_mapstore_client/client/js/components/ZoomTo/index.js
geonode_mapstore_client/client/js/epics/gnsave.js
geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
geonode_mapstore_client/client/js/reducers/__tests__/gnresource-test.js
geonode_mapstore_client/client/js/reducers/gnresource.js

Also added a callback to close map thumbnail view once set thumbnail is complete.

Fixed Map Thumbnail bug

---

geonode_mapstore_client/client/js/apps/gn-catalogue.js
geonode_mapstore_client/client/js/apps/gn-dashboard.js
geonode_mapstore_client/client/js/apps/gn-document.js
geonode_mapstore_client/client/js/apps/gn-geostory.js
geonode_mapstore_client/client/js/apps/gn-home.jsx
geonode_mapstore_client/client/js/apps/gn-map.js
geonode_mapstore_client/client/js/utils/AppUtils.js
geonode_mapstore_client/context_processors.py
geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html

This PR adds a dynamic function that loads the current intl properties dynamically of the current selected locale

Decuple locales from MapStore core translations

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/routes/UploadDataset.jsx
geonode_mapstore_client/client/js/routes/UploadDocument.jsx
geonode_mapstore_client/client/js/routes/upload/PendingUploadCard.jsx
geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
geonode_mapstore_client/client/js/routes/upload/UploadContainer.jsx
geonode_mapstore_client/client/js/routes/upload/UploadListContainer.jsx
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/less/_upload.less

This PR introduces transmission progress tracking inside upload container.
It also captures 'file size exceeded' error

Transmission progress

---

geonode_mapstore_client/client/js/routes/UploadDataset.jsx
geonode_mapstore_client/client/js/routes/UploadDocument.jsx
geonode_mapstore_client/client/js/routes/upload/PendingUploadCard.jsx
geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
geonode_mapstore_client/client/js/routes/upload/UploadContainer.jsx
geonode_mapstore_client/client/js/routes/upload/UploadListContainer.jsx
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json

- added file sizes
- changed warning `btn` to primary
- updated message

Dataset and Document Upload UI changes

---

geonode_mapstore_client/client/js/routes/UploadDataset.jsx

Fixes a bug causing processed dataset uploads to disappear from list when one upload errors out

Fixed dataset error upload bug

---

geonode_mapstore_client/context_processors.py
geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html
geonode_mapstore_client/utils.py

Fixes #776] Include the upload limits inside __GEONODE_CONFIG__

---

geonode_mapstore_client/client/js/routes/UploadDataset.jsx
geonode_mapstore_client/client/js/routes/UploadDocument.jsx
geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
geonode_mapstore_client/client/js/routes/upload/UploadContainer.jsx
geonode_mapstore_client/client/js/routes/upload/UploadListContainer.jsx
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json

Prevents users from uploading files exceeding the limit

Added file upload limit

---

geonode_mapstore_client/client/js/routes/upload/UploadContainer.jsx
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/themes/geonode/less/_upload.less

- Upload button changed to primary
- Upload button disabled when file size exceeds
- Upload Documents and Upload Dataset links updated inside "Add Resource"

Upload feature fixes

---

geonode_mapstore_client/client/js/components/CardGrid/CardGrid.jsx
geonode_mapstore_client/client/js/components/FeaturedList/FeaturedList.jsx
geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx
geonode_mapstore_client/client/js/components/Menu/DropdownList.jsx
geonode_mapstore_client/client/js/components/Menu/MenuItem.js
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/themes/geonode/less/_base.less
geonode_mapstore_client/client/themes/geonode/less/_menu.less
geonode_mapstore_client/client/themes/geonode/less/_search-bar.less

This PR fixes responsive issues on catalogue page

Issues with responsiveness on card view

---

geonode_mapstore_client/templates/geonode-mapstore-client/snippets/brand_navbar.html

This PR adds a responsive fix for header inside django template

Fixed header responsive issue

---

geonode_mapstore_client/client/js/routes/Viewer.jsx
geonode_mapstore_client/client/themes/geonode/less/_base.less
geonode_mapstore_client/client/themes/geonode/less/_menu.less

The search bar is set to none on smaller screens in `<Viewer />`

Finalized header responsiveness

---

geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx
geonode_mapstore_client/client/js/epics/gnresource.js
geonode_mapstore_client/client/js/plugins/actionnavbar/buttons.jsx
geonode_mapstore_client/client/js/plugins/index.js
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fi-FI.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.hr-HR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/static/mapstore/translations/data.nl-NL.json
geonode_mapstore_client/client/static/mapstore/translations/data.pt-PT.json
geonode_mapstore_client/client/static/mapstore/translations/data.sk-SK.json
geonode_mapstore_client/client/static/mapstore/translations/data.sv-SE.json
geonode_mapstore_client/client/static/mapstore/translations/data.vi-VN.json
geonode_mapstore_client/client/static/mapstore/translations/data.zh-ZH.json
geonode_mapstore_client/client/themes/geonode/less/_base.less
geonode_mapstore_client/client/themes/geonode/less/_legend.less

This PR adds the filter plugin to the dataset page

[Fixes #791] Add Filter button to dataset viewer

---

geonode_mapstore_client/client/js/plugins/SaveAs.jsx
geonode_mapstore_client/client/js/plugins/save/SaveModal.jsx

Pressing enter key while cloning, will now clone the data

Pressing Enter key when cloning does not clone the data

---

geonode_mapstore_client/apps.py

References: https://github.com/GeoNode/geonode/issues/8719

Configure specific labels for document permissions

---

geonode_mapstore_client/templates/geonode-mapstore-client/snippets/brand_navbar.html
geonode_mapstore_client/templates/geonode-mapstore-client/snippets/search_bar.html

You This PR includes a fix for autocomplete feature on responsive search bar

Autocomplete is not working on responsive search bar

---

geonode_mapstore_client/client/themes/geonode/less/_details-panel.less

This PR fixes inconsistencies in Title and Abstract editing

Fix visual artefacts edit input box for title and abstract

---

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx

Editing is disabled inside resource info panel

Render HTML abstract content

---

geonode_mapstore_client/client/js/actions/gnresource.js
geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/components/ActionButtons/ActionButtons.jsx
geonode_mapstore_client/client/js/components/CardGrid/CardGrid.jsx
geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
geonode_mapstore_client/client/js/components/FeaturedList/Cards.jsx
geonode_mapstore_client/client/js/components/FeaturedList/FeaturedList.jsx
geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx
geonode_mapstore_client/client/js/epics/__tests__/resourceservice-test.js
geonode_mapstore_client/client/js/epics/resourceservice.js
geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
geonode_mapstore_client/client/js/reducers/resourceservice.js
geonode_mapstore_client/client/js/routes/Detail.jsx
geonode_mapstore_client/client/js/routes/Home.jsx
geonode_mapstore_client/client/js/routes/catalogue/ConnectedCardGrid.jsx
geonode_mapstore_client/client/js/selectors/__tests__/resourceservice-test.js
geonode_mapstore_client/client/js/selectors/resourceservice.js
geonode_mapstore_client/client/js/utils/ResourceServiceUtils.js
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/less/_details-panel.less

This PR introduces a download feature for resources as:
- action button on resource card
- download button in resource detail panel

Implement direct download action buttons

---

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
geonode_mapstore_client/client/js/plugins/FitBounds.jsx
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/themes/geonode/less/_details-panel.less

This PR expands validation for extent inside `FitBounds` and also excludes map thumbnail feature for ArcGIS resources.

Investigate error with ArcGIS remote layer

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/components/ActionButtons/ActionButtons.jsx
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

This PR removes auth requirement for download action in resource cards.

Download should be visible in card menu to anonymous users if the permission is available

---

geonode_mapstore_client/context_processors.py
geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html

[Fixes #868] Add default upload parallelism limit inside __GEONODE_CONFIG__

---

geonode_mapstore_client/client/js/routes/UploadDataset.jsx
geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
geonode_mapstore_client/client/js/utils/ErrorUtils.js
geonode_mapstore_client/client/js/utils/__tests__/ErrorUtils-test.js

This PR adopts upload API error codes

Adopt Upload API error codes

---

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

This PR add KML format to layer download options.

Enable KML format for WPS export of vector layers

---

geonode_mapstore_client/client/js/routes/UploadDataset.jsx
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js

This PR fixes issues with dataset uploads not updating correctly

Dataset uploads are not updated appropriately

---

geonode_mapstore_client/client/js/plugins/VisualStyleEditor.jsx

This PR fixes irrelevant style message shown on datasets. The message only shows in map visual style editing.

Irrelevant message in dataset style editor

---

geonode_mapstore_client/migrations/0001_clean_prev_version_geoapps.py

[Fixes #905] Integrity db error between geoapps tables on upgrade from 3.x to 4.x

---

geonode_mapstore_client/client/js/plugins/Legend.jsx
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/themes/geonode/less/_legend.less

This PR introduces layer visibility and opacity toggles inside Legend plugin

[Backport 4.x][Fixes #898] Add layer visibility toggle to legend component

---

geonode_mapstore_client/client/js/plugins/VisualStyleEditor.jsx

This PR fixes irrelevant style message shown on datasets. The message only shows in map visual style editing.

[Backport 4.x][Fixes #911] Irrelevant message in dataset style editor

---

geonode_mapstore_client/client/js/routes/UploadDataset.jsx
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js

This PR fixes issues with dataset uploads not updating correctly

[Backport 4.x][Fixes #910] Dataset uploads are not updated appropriately

---

geonode_mapstore_client/client/js/components/FiltersForm/FiltersForm.jsx
geonode_mapstore_client/client/js/components/FiltersForm/__tests__/FiltersForm-test.jsx
geonode_mapstore_client/client/themes/geonode/less/_filter-form.less

 [Backport 4.x][Fixes #933] Clear filters button not well aligned and not visible

---

geonode_mapstore_client/client/js/plugins/Share.jsx
geonode_mapstore_client/client/js/plugins/share/SharePageLink.jsx
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/less/_share.less

ref #947 
This PR shows direct share links inside Share Panel

[Backport 4.x][Fixes #947]: Show direct links and embed links inside Share panel

---

geonode_mapstore_client/migrations/0002_migrate_map_blob.py

Fix failing migration 0002_migrate_map_blob.py

[Fixes #987] Failing migration 0002_migrate_map_blob.py

---

geonode_mapstore_client/context_processors.py
geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html

[Backport 4.x][Fixes #991] Add CREATE_LAYER setting to geonode_config

---

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

[Fixes #1020] Show invalid bbox warning on the overview of the dataset

---

geonode_mapstore_client/client/js/plugins/Share.jsx
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/less/_share.less

Share links have been adjusted according to https://github.com/GeoNode/geonode-mapstore-client/issues/968#issue-1232475692

[Fixes #968] Adjustments to links inside Share Panel

---

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

[Fixes 1023] Change the lable for the GML FeatureCollection export format

---

geonode_mapstore_client/client/js/apps/gn-document.js
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

`gn-docment` app has been extended

[Fixes 1053] Include base support for localization in gn-document app entry

---

geonode_mapstore_client/context_processors.py

Function rename based on this comment: https://github.com/GeoNode/geonode/pull/9612/files/9ca2d7c8fe5d8c15c4546d13482f7f0a0b22045d#r914838740

rename function to get dataset supported types

---

geonode_mapstore_client/client/js/components/MainErrorView/MainErrorView.jsx
geonode_mapstore_client/client/js/components/MainErrorView/index.js
geonode_mapstore_client/client/js/components/MainEventView/MainEventView.jsx
geonode_mapstore_client/client/js/components/MainEventView/index.js
geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx
geonode_mapstore_client/client/js/components/MediaViewer/__tests__/Media-test.jsx
geonode_mapstore_client/client/js/routes/Viewer.jsx
geonode_mapstore_client/client/package.json
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
geonode_mapstore_client/client/themes/geonode/less/_media-viewer.less

This PR implements https://github.com/geonode/geonode-mapstore-client/issues/955#issuecomment-1161849063
ref #955

[Fixes 955] Blured icon images

---

geonode_mapstore_client/client/js/apps/gn-document.js
geonode_mapstore_client/client/package.json
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

`gn-docment` app has been extended
ref #1053

[Backport 4.x][Fixes 1053] Include base support for localization in gn-document app entry

---

geonode_mapstore_client/client/js/actions/gnsearch.js
geonode_mapstore_client/client/js/epics/resourceservice.js
geonode_mapstore_client/client/js/reducers/gnsearch.js
geonode_mapstore_client/client/package.json

Total number of resources is updated after deletion.

[Fixes 1051] Total number of resources and list of resources should be updated after deleting a resource from the list

---

geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx

Spinner only keeps track of progress

[Fixes 1085] Spinner is missing during the upload phase

---

geonode_mapstore_client/client/themes/geonode/less/_base.less

The color picker has been fixed

[Fixes 1058] Problem with color picker in Bar and Pie chart

---

geonode_mapstore_client/client/js/plugins/Legend.jsx
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json

[Fixes 1072] Dataset legend must show the dataset's title instead of Geoserver's layername 

---

geonode_mapstore_client/context_processors.py
geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html

[Backport 4.x] [Fixes #1064] Expose supported upload file formats as configurations

---

geonode_mapstore_client/client/themes/geonode/less/_resource-card.less

Fixed text overflow on screens above 1650p

[Fixes 1089] Fix text overflow in resource Delete dialog box

---

geonode_mapstore_client/client/themes/geonode/less/_resource-card.less

Fixed text overflow on screens above 1650p
ref #1089

[Backport 4.x][Fixes #1089] Fix text overflow in resource Delete dialog box

---

geonode_mapstore_client/client/js/actions/gnresource.js
geonode_mapstore_client/client/js/epics/__tests__/gnresource-test.js
geonode_mapstore_client/client/js/epics/gnresource.js
geonode_mapstore_client/client/js/epics/gnsave.js
geonode_mapstore_client/client/js/reducers/gnsearch.js

The catalogue state is updated after save
ref #1038

[Backport 4.x][Fixes #1038] Reload catalogue after saving a resource

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/routes/UploadDataset.jsx
geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
geonode_mapstore_client/client/js/routes/upload/UploadListContainer.jsx
geonode_mapstore_client/client/js/utils/ErrorUtils.js
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js

A separate upload flow has been included in the client for Geopackages using the execution status endpoint to track their upload statuses.
ref #1115

[Fixes 1115] Upload progress for GKPG based on execution requests

---

geonode_mapstore_client/client/js/plugins/save/SaveModal.jsx

Issues with pressing enter to clone in save modal have been fixed.

[Fixes 1122] Issues with pressing Enter in Clone dialog

---

geonode_mapstore_client/client/js/plugins/actionnavbar/buttons.jsx
geonode_mapstore_client/client/js/plugins/index.js
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

There is a duplicated LayerDownload that has been called DataDownload, this PR removes the duplication

[Fixes #1156] Remove duplicated data download plugin

---

geonode_mapstore_client/client/js/epics/datasetscatalog.js
geonode_mapstore_client/client/js/epics/layersettings.js
geonode_mapstore_client/client/js/epics/visualstyleeditor.js
geonode_mapstore_client/client/js/selectors/__tests__/mapsave-test.js
geonode_mapstore_client/client/js/selectors/mapsave.js
geonode_mapstore_client/client/js/selectors/resource.js
geonode_mapstore_client/client/js/utils/LayoutUtils.js

`availableStyles` property was removed from the data payload, this PR reintroduced it in the saving process

[Backport 4.x][Fixes #1168] Some issues with map layer style editing 

---

geonode_mapstore_client/client/js/epics/favorite.js

[Fixes 1195] Counter keeps increasing when favorite icon is clicked multiple times

---

geonode_mapstore_client/client/js/epics/favorite.js

[Backport 4.0.x][Fixes 1195] Counter keeps increasing when favorite icon is clicked multiple times 

---

docs/customizations/theme.html

The theme variables are defined in the root

[Fixes 1147] Theme override styles from customization app needs some improvement

---

geonode_mapstore_client/context_processors.py
geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html

[Fixes #1211] Add THUMBNAIL_SIZE configurations to __GEONODE_CONFIG__

---

geonode_mapstore_client/client/js/plugins/LayerSettings.jsx
geonode_mapstore_client/client/js/plugins/VisualStyleEditor.jsx
geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json
geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json
geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json
geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json
geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json

[Fixes 1143] Add Hint on settings and style icons on editing map layer

---

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

Timeline has been activated in Map and Dataset preview and embed views

[Fixes 1226] Embedded maps should have the timeline plugin

---

geonode_mapstore_client/client/js/epics/gnresource.js

`/api/v2/resources/{pk}/permissions` calls are avoided for anonymous users

[Fixes 1213] Avoid executing permissions request for anonymous users

---

geonode_mapstore_client/client/js/epics/gnresource.js

`/api/v2/resources/{pk}/permissions` calls are avoided for anonymous users
ref #1213

[Backport 4.0.x][Fixes #1213] Avoid executing permissions request for anonymous users

---

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

Timeline has been activated in Map and Dataset preview and embed views

[Backport 4.0.x][Fixes 1226] Embedded maps should have the timeline plugin

---

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/templatetags/get_menu_json.py

Remote services is moved to Add Resources dropdown

[Fixes 1247] Move Remote Service under Add Resource

---

geonode_mapstore_client/client/js/routes/UploadDataset.jsx
geonode_mapstore_client/client/js/routes/UploadDocument.jsx
geonode_mapstore_client/client/js/utils/FileUtils.js
geonode_mapstore_client/client/js/utils/__tests__/FileUtils-test.js

This PR fixes issue with file extension in uppercase

[Fixes 1254] Fix issue with upload failing when file extension is in uppercase

---

geonode_mapstore_client/templates/geonode-mapstore-client/snippets/language_selector.html

[Fixes #1224] Change language on time series page not working

---

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx

[Fixes 1268] Fix metedata view buttons bug

---

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/templatetags/get_menu_json.py

Remote services is moved to Add Resources dropdown
ref #1247

[Backport 4.0.x][Fixes #1247] Move Remote Service under Add Resource (#1248)

---

geonode_mapstore_client/client/js/plugins/Share.jsx

The inconsistencies in icons inside group permissions search panel are fixed

[Fixes 1278] Inconsistencies in group permissions search panel 

---

geonode_mapstore_client/client/js/plugins/Share.jsx

The inconsistencies in icons inside group permissions search panel are fixed

[Backport 4.0.x][Fixes #1278] Inconsistencies in group permissions search panel

---

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx

* Fixed metadata preview
* Fixed button in resource card

[Backport 4.0.x][Fixes 1268] Fix metadata view buttons bug (#1269)

---

geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json

[Fixes 1286] "style" is lowercase, while the other menu items have the second term uppercase

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js

[Fixes #1267] Filter executionrequest by source 

---

geonode_mapstore_client/client/js/apps/gn-catalogue.js
geonode_mapstore_client/client/js/apps/gn-dashboard.js
geonode_mapstore_client/client/js/apps/gn-document.js
geonode_mapstore_client/client/js/apps/gn-geostory.js
geonode_mapstore_client/client/js/apps/gn-map.js
geonode_mapstore_client/client/js/components/Router/Router.jsx
geonode_mapstore_client/client/js/utils/AppRoutesUtils.js

Protected routes has been implemented

[Fixes 1303] Redirect users to Login page on accessing restricted pages 

---

geonode_mapstore_client/client/js/components/Router/Router.jsx
geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx

Also fixes double slash in redirected upload page

[Fixes 1335] Pagination buttons on empty catalogue page

---

geonode_mapstore_client/client/js/components/CardGrid/CardGrid.jsx
geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx
geonode_mapstore_client/client/js/components/MainLoader/MainLoader.jsx
geonode_mapstore_client/client/js/epics/gnsearch.js
geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/client/themes/geonode/less/_base.less
geonode_mapstore_client/client/themes/geonode/less/_card-grid.less
geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
geonode_mapstore_client/client/themes/geonode/less/_filter-form.less
geonode_mapstore_client/client/themes/geonode/less/_home-container.less
geonode_mapstore_client/client/themes/geonode/less/_menu.less
geonode_mapstore_client/client/themes/geonode/less/_resource-card.less
geonode_mapstore_client/client/themes/geonode/less/_resources-grid.less

This PR introduces the switch between infinity scroll and pagination based on the resources layout catalog type when the ResourceGrid uses pagination cfg sets to undefined

Implement switch pagination based on the resources layout catalog type

---

geonode_mapstore_client/client/js/epics/gnresource.js

This PR adds a workflow to close open panels when another is open

[Fixes 1306] Annotations and add dataset form is not opened when info is showing

---

geonode_mapstore_client/client/js/components/ActionButtons/ActionButtons.jsx
geonode_mapstore_client/client/js/plugins/SaveAs.jsx
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
geonode_mapstore_client/client/static/mapstore/configs/localConfig.json

This PR improves the checks for clone and save as actions

[Backport 4.0.x][Fixes #1308] Clone option in the list view is missing on Maps for non admin users (#1350)

---

geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
geonode_mapstore_client/client/themes/geonode/less/_base.less

Added custom class name flag for pagination

[Fixes #1362] Broken pagination in profile page

---

geonode_mapstore_client/client/js/plugins/DeleteResource.jsx

This PR adds a side effect to remove the `d` query params from url. Once the `d`etail query param is removed the panel is automatically close

[Fixes #1358] Preview is not automatically closed when a resource is deleted

---

geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
geonode_mapstore_client/client/themes/geonode/less/_base.less

Added custom class name flag for pagination
#1362

[Backport 4.1.x][Fixes #1362] Broken pagination in profile page (#1368)

---

geonode_mapstore_client/client/js/plugins/DeleteResource.jsx

This PR adds a side effect to remove the `d` query params from url. Once the `d`etail query param is removed the panel is automatically close
#1358

[Backport 4.1.x][Fixes #1358] Preview is not automatically closed when a resource is deleted (#1369)

---

geonode_mapstore_client/static/mapstore/configs/localConfig.json

[Fix #1388] Make the View menu visible also to users with edit permissions

---

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsInfo.jsx
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
geonode_mapstore_client/client/themes/geonode/less/_resources-grid.less
geonode_mapstore_client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json
geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json
geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json

This PR adds a `View full metadata` link on the details info tab
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?** (check one with "x", remove the others)
- #1412  
**Example**
**Does this PR introduce a breaking change?** (check one with "x", remove the other)

#1412: DetailView - Add link to the metadata page

---

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx

Fix temporal extent representation in info panel

---

geonode_mapstore_client/static/mapstore/configs/localConfig.json

This PR fixes the incorrect translations path for linked resource tab
- #1431

#1431: Fix translation for Linked resources tab

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/epics/__tests__/sync-test.js
geonode_mapstore_client/client/js/epics/gnsync.js
geonode_mapstore_client/client/js/selectors/__tests__/resource-test.js
geonode_mapstore_client/client/js/selectors/resource.js

#1395
This PR includes following fixes:
- reduce number of requests on sync
- fix bug related to update of maps on dashboards

Fix #1395 Dashboard sync not working

---

geonode_mapstore_client/client/js/actions/gnresource.js
geonode_mapstore_client/client/js/epics/__tests__/detailviewer-test.js
geonode_mapstore_client/client/js/epics/__tests__/gnresource-test.js
geonode_mapstore_client/client/js/epics/detailviewer.js
geonode_mapstore_client/client/js/epics/gnresource.js
geonode_mapstore_client/client/js/epics/gnsearch.js
geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
geonode_mapstore_client/client/js/utils/APIUtils.js

Fix #1456 Multiple requests for linked resources

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/epics/__tests__/sync-test.js
geonode_mapstore_client/client/js/epics/gnsync.js
geonode_mapstore_client/client/js/selectors/__tests__/resource-test.js
geonode_mapstore_client/client/js/selectors/resource.js

#1395
This PR includes following fixes:
- reduce number of requests on sync
- fix bug related to update of maps on dashboards

[Backport 4.1.x] Fix #1395 Dashboard sync not working (#1452)

---

geonode_mapstore_client/client/js/actions/gnresource.js
geonode_mapstore_client/client/js/epics/__tests__/detailviewer-test.js
geonode_mapstore_client/client/js/epics/__tests__/gnresource-test.js
geonode_mapstore_client/client/js/epics/detailviewer.js
geonode_mapstore_client/client/js/epics/gnresource.js
geonode_mapstore_client/client/js/epics/gnsearch.js
geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
geonode_mapstore_client/client/js/utils/APIUtils.js

[Backport 4.1.x] Fix #1456 Multiple requests for linked resources (#1457)

---

geonode_mapstore_client/client/js/components/CardGrid/CardGrid.jsx
geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx
geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
geonode_mapstore_client/client/themes/geonode/less/_resources-grid.less

This PR adds panel component feature to ResourceGrid
- #1471

#1471: Resource grid as panel components

---

geonode_mapstore_client/client/js/api/geonode/user/index.js
geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/apps/gn-catalogue.js
geonode_mapstore_client/client/js/apps/gn-geostory.js
geonode_mapstore_client/client/js/apps/gn-map.js
geonode_mapstore_client/client/js/utils/APIUtils.js
geonode_mapstore_client/client/js/utils/AppUtils.js
geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html

This PR refactors the code to perform initial requests with geonode config instead of default values.
- #1470

#1470: Initial requests uses geonode config values

---

geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js

This PR ensures map layers gets correct feature info format
- #1483

#1483: Feature info format on map layer

---

geonode_mapstore_client/client/js/routes/UploadDataset.jsx

The order has been implemented backend side so not needed anymore

Revert fix #1480

---

geonode_mapstore_client/client/js/routes/UploadDocument.jsx

This PR fixes the filtering of uploaded urls from the list
- #1477

#1477: Filter upload urls on success upload

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/routes/UploadDataset.jsx

[Fixes #1531] Remove the call to the upload view for listing pending uploads

---

geonode_mapstore_client/client/js/components/Menu/DropdownList.jsx
geonode_mapstore_client/client/js/components/Menu/MenuItem.js
geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
geonode_mapstore_client/client/themes/geonode/less/_menu.less
geonode_mapstore_client/static/mapstore/configs/localConfig.json

This PR adds improvements to the layout of the action bar menu
- #1536

#1536: Improvements to the layout of the action bar menus

---

geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js

This PR adds opacity, order and visibility property to maplayer when saving the map
- #1521

#1521: Save maplayer with additional info

---

geonode_mapstore_client/client/js/utils/APIUtils.js

#1551: Sort param serializer fix (#1552)

[Backport 4.1.x] #1551: Sort param serializer fix (#1552)

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/components/MediaViewer/Scene3DViewer.jsx
geonode_mapstore_client/client/js/routes/Catalogue.jsx
geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html

This PR adds routing to Catalog route component to handle redirection when catalog home redirect url is configured, like subsites 
- #1583

#1583: Implement catalogue home redirect based on config

---

geonode_mapstore_client/client/js/plugins/DownloadResource.jsx

This PR fixes the minor rendering issue with the download button. 
**Fixed** - Ajax safe URLs are rendered as external link

Fix ajax safe download button render

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/components/Accordion/Accordion.jsx
geonode_mapstore_client/client/js/components/FiltersForm/FilterItems.jsx
geonode_mapstore_client/client/js/components/FiltersForm/__tests__/FilterItems-test.jsx
geonode_mapstore_client/client/js/epics/gnsearch.js
geonode_mapstore_client/client/js/hooks/useDeepCompareEffect.js

This PR fixes facet filtering in accordion and select
Address the following too,
- Accordion component rendering
- Reduces unnecessary facetbykey calls fired 
- #1598

#1598: Facet fixes on different filter type

---

geonode_mapstore_client/client/js/components/FiltersForm/FilterItems.jsx
geonode_mapstore_client/client/js/components/Tabs/Tabs.jsx

This PR enhances the `Tabs` component
- New property `persistSelection` is introduced to configure tab selection persistence, as earlier the tab is  persisted by default
- Code refactored to enhance the conditional rendering of the tab component. This helps in rendering the map component properly every time as turning off animation alone was not enough.

#1607: Tabs component enhancement

---

geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx
geonode_mapstore_client/client/js/components/MediaViewer/PdfViewer.jsx

This PR fixes the regression introduced in handling external source type to show document preview
- #1627

#1627: Regression fix for external and local document preview

---

geonode_mapstore_client/static/mapstore/configs/localConfig.json

#1621: Implement search service configuration for Maps (#1622)

[Backport 4.2.x] #1621: Implement search service configuration for Maps (#1622)

---

geonode_mapstore_client/client/js/plugins/Share.jsx
geonode_mapstore_client/client/js/selectors/__tests__/resource-test.js
geonode_mapstore_client/client/js/selectors/resource.js

#1635: Share option is available only to user with manage permissions (#1636)

[Backport 4.2.x] #1635: Share option is available only to user with manage permissions (#1636)

---

geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx
geonode_mapstore_client/client/js/components/MediaViewer/PdfViewer.jsx

This PR fixes the regression introduced in handling external source type to show document preview
- #1627

[Backport 4.2.x] #1627: Regression fix for external and local document preview (#1628)

---

geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx

relates to https://github.com/GeoNode/geonode/issues/11853
Enable group facets

Enable group facets

---

geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx
geonode_mapstore_client/client/js/utils/FileUtils.js
geonode_mapstore_client/client/js/utils/__tests__/FileUtils-test.js

This PR allows the audio format to be viewed via react-player (video component) as requested
- #1678

#1678: Enable react-player for audio file resources

---

geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx
geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json
geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json
geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json

This PR adds mapviewers to filter panel
- #1699

#1699: Add mapviewers to filter panel

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/epics/gnresource.js
geonode_mapstore_client/client/js/plugins/MapViewerConfiguration.jsx
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js

The linked resources are fetched along with resource call avoid separate calls in the map viewer page for map and mapviewer
- #1704

#1704: Enhance fetching linked resources in map viewer

---

geonode_mapstore_client/client/js/plugins/LayerSettings.jsx
geonode_mapstore_client/client/js/utils/PluginsContextUtils.js
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/static/mapstore/configs/pluginsConfig.json

This PR allows render layer setting/TOCItemSetting based on the dataset/layer selected
- #1720

#1720: Improve layer setting visualisation

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/utils/APIUtils.js

This PR updates MS submodule to latest 2024.01.xx with axios version updated to 0.28.1 and update with new paramSerialization as an object instead of function. This fixes indefinite loading of resources
- #1735

#1735: Fix - Map and other resources are loading indefinitely

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/epics/gnresource.js

This PR optimizes the response data of the mapviewer call in the Map resource
- #1745

#1745: Optimize response of the geoapps call in Map

---

geonode_mapstore_client/apps.py

This is connected to https://github.com/GeoNode/geonode/pull/12254

Configure the proxy settings to support the MS catalog plugin

---

.github/workflows/build.yml
.github/workflows/test.yml
geonode_mapstore_client/client/.npmrc

Update node version to 20 in build and test workflow

Support of node 20

---

geonode_mapstore_client/client/js/plugins/index.js

Update MapStore submodule to version 2024.01.01

[4.3.x] update submodule to version 2024.01.01

---

geonode_mapstore_client/client/js/api/geonode/user/index.js
geonode_mapstore_client/client/js/routes/Viewer.jsx

This PR fixes the primary key comparison in the Viewer component that was causing the infinite loading of dataset

Fix #1827 Infinite loading for dataset embed

---

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsAssets.jsx
geonode_mapstore_client/client/js/components/DetailsPanel/DetailsInfo.jsx
geonode_mapstore_client/client/js/epics/resourceservice.js
geonode_mapstore_client/client/js/plugins/DownloadResource.jsx
geonode_mapstore_client/client/js/reducers/gnresource.js
geonode_mapstore_client/client/js/utils/FileUtils.js
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/js/utils/__tests__/FileUtils-test.js
geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
geonode_mapstore_client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json
geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json
geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json

This PR implements the assets tab in the details panel

Fix #1825 Implement Assets tab

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/routes/UploadDataset.jsx
geonode_mapstore_client/client/js/routes/UploadDocument.jsx
geonode_mapstore_client/client/js/routes/upload/ErrorMessageWithTooltip.jsx
geonode_mapstore_client/client/js/routes/upload/PendingUploadFile.jsx
geonode_mapstore_client/client/js/routes/upload/PendingUploadUrl.jsx
geonode_mapstore_client/client/js/routes/upload/UploadContainer.jsx
geonode_mapstore_client/client/js/utils/FileUtils.js
geonode_mapstore_client/client/js/utils/UploadUtils.js
geonode_mapstore_client/client/js/utils/__tests__/UploadUtils-test.js
geonode_mapstore_client/client/themes/geonode/less/_upload.less
geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json
geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json
geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json

This PR includes following changes:
- refactor of the remote document upload components
- introduction of remote dataset upload limited to 3D Tiles

Implement the UI to create 3dtiles resources from URL

---

geonode_mapstore_client/templates/base.html
geonode_mapstore_client/templates/geonode-mapstore-client/snippets/search_bar.html

- include the _geonode_config.html in legacy pages
- review the search workflow optimizing the requests

Fix #1845 Search bar executes multiple API requests

---

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsSettings.jsx
geonode_mapstore_client/client/js/plugins/detailviewer/tabComponents.js
geonode_mapstore_client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json
geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json
geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json

This PR replaces `Management` with `Settings` tab

Fix #1847 Replace management with settings tab

---

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsSettings.jsx
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json
geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json
geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json

The settings labels have been simplified and the current labels have been used as tooltip

Fix #1847 simplify labels and add tooltips

---

geonode_mapstore_client/client/js/epics/gnsave.js

[Backport 4.4.x] Fix #1857 After saving a resource the resource information must be refreshed

---

.gitmodules
geonode_mapstore_client/client/.npmrc
geonode_mapstore_client/client/package.json

Update MapStore to version 2024.02.xx

Update mapstore to version 2024.02.xx

---

geonode_mapstore_client/static/mapstore/configs/localConfig.json

This PR aligns query panel configuration with the MapStore submodule configuration

Update query panel configuration

---

.gitmodules
geonode_mapstore_client/client/js/api/geonode/v2/constants.js
geonode_mapstore_client/client/js/plugins/Operation/index.jsx
geonode_mapstore_client/client/js/routes/UploadDataset.jsx
geonode_mapstore_client/client/themes/geonode/less/_operation.less
geonode_mapstore_client/client/themes/geonode/less/_upload.less
geonode_mapstore_client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json
geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json
geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json

- review style of upload table
- changed the Replace label with Replace Dataset
- update uploads url with api/v2 version
- updated mapstore submodule

Fix #1886 Impreovements to the new upload and replace UI

---

.gitmodules

This PR updates MS submodule to latest stable release [v2024.02.00](https://github.com/geosolutions-it/MapStore2/tree/v2024.02.00)
- #1894

Update 4.4.x MS submodule to release 2024.02.00

---

geonode_mapstore_client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json

This PR rename's the settings tab to `Management`

Rename the Settings tab to Management

---

geonode_mapstore_client/client/themes/geonode/less/_metadata.less

This PR capitalizes the titles of the metadata form regardless of the response

Metadata form titles are capitalized

---

geonode_mapstore_client/client/js/plugins/index.js

This PR adds missing container override to include filter layer in dataset viewer
- #1913

#1913: Fix - Dataset filtering option missing

---

geonode_mapstore_client/client/themes/geonode/less/_metadata.less

This PR fixes style issue when plain array of non autocomplete fields

Plain arrays (non autocomplete) fix render

---

geonode_mapstore_client/client/js/plugins/MetadataEditor/containers/MetadataEditor.jsx

This PR fixes the rendering of the root errors in the form

Fix root errors rendering

---

geonode_mapstore_client/client/js/plugins/Legend.jsx
geonode_mapstore_client/client/js/utils/ResourceUtils.js
geonode_mapstore_client/client/package.json

This PR backports latest changes from MS master to include Legend filtering of WMS layer
###Issue
- #1907

#1907: Legend filtering for GeoServer WMS layers

---

geonode_mapstore_client/client/js/plugins/Legend.jsx
geonode_mapstore_client/client/js/utils/ResourceUtils.js

#1907: Legend filtering for GeoServer WMS layers (#1934)

[Backport 4.4.x] #1907: Legend filtering for GeoServer WMS layers

---

geonode_mapstore_client/client/js/plugins/VisualStyleEditor.jsx

This PR fixes the exception thrown when selecting the style inside layer setting of the TOC
- #1964

#1964: Fix - Exception when selecting style inside layer setting of the TOC

---

geonode_mapstore_client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/static/mapstore/configs/pluginsConfig.json

This PR updates MS submodule to include StyleEditor feature to restrict editing of default style of the dataset in the map
- #1975

#1975: Restrict default style editing of the dataset from the map

---

geonode_mapstore_client/client/js/plugins/MetadataEditor/containers/MetadataEditor.jsx
geonode_mapstore_client/client/js/plugins/MetadataEditor/containers/MetadataUpdateButton.jsx

When error is due to 422, show the error message as a warning
- #2002

Update with a warning when 422

---

geonode_mapstore_client/static/mapstore/configs/localConfig.json

#118: Remove duplicated fullscreen button

---

geonode_mapstore_client/client/themes/geonode/less/_metadata.less

Update metadata side panel style

Fix - Metadata side panel list style

---

geonode_mapstore_client/client/themes/geonode/less/_resources-catalog.less
geonode_mapstore_client/templates/geonode-mapstore-client/snippets/footer.html

**Homepage**
**Resource page**

Add space to avoid overlapping of resource and pagination

---

geonode_mapstore_client/static/mapstore/configs/localConfig.json

The button `View Data` is visible also for remote layers

Enable view data for remote layers

---

geonode_mapstore_client/client/js/epics/gnresource.js

This PR fixes the resource card highlight when detail in open
- https://github.com/geosolutions-it/geonode-team-internal-issues/issues/131

Fix - Resource cards are not highlighted when the details are open

---

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsLocations.jsx

This PR allows zoom and pan interaction when the resource perms is read-only 
- #2021

#2021: Enable zoom and pan of the Location map when read-only

---

geonode_mapstore_client/client/js/plugins/ResourceDetails/containers/DetailsPanel.jsx

This PR updates geonode-home to latest MS master aligning all the changes made to custom branch

Update geonode-home to latest MS master

---

tutorials/theme.html

This PR fixes the version of the tutorial theme to 4.4.x

Fix tutorial theme

---

geonode_mapstore_client/client/js/api/geonode/v2/index.js
geonode_mapstore_client/client/js/epics/__tests__/gnresource-test.js
geonode_mapstore_client/client/js/epics/gnresource.js
geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json
geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json
geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json

This PR fixes the remove thumbnail from a resource
- https://github.com/geosolutions-it/geonode-team-internal-issues/issues/140

Remove thumbnail from a resource

---

geonode_mapstore_client/client/js/epics/gnresource.js
geonode_mapstore_client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json
geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json
geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json

This PR updates menu items of the dataset navbar. Allow map layer setting redirection with edit style
- #2020

#2020 - Update edit menu of the dataset and layer settings

---

.gitmodules
geonode_mapstore_client/client/js/plugins/ResourceDetails/containers/DetailsPanel.jsx

This PR updates MS submodule to latest stable (2025.01.xx)

Updated MS submodule to latest stable

---

geonode_mapstore_client/templatetags/get_menu_json.py

This PR was created according to this issue [#13111](https://github.com/GeoNode/geonode/issues/13111) from the GeoNode repo

Remove inbox link from the user menu

---

geonode_mapstore_client/apps.py
geonode_mapstore_client/views.py

This PR was created according to this issue: #2071

[Fixes #2071] Fixing resources catalog page routing

---

geonode_mapstore_client/client/themes/geonode/less/_variables.less

Retain hero background color

---

geonode_mapstore_client/client/js/plugins/MetadataEditor/containers/MetadataUpdateButton.jsx
geonode_mapstore_client/client/js/plugins/MetadataEditor/index.js
geonode_mapstore_client/static/mapstore/configs/localConfig.json
geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json
geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json
geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json
geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json
geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json
geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json
geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json

This PR updates metadata feedback on update operation

Metadata update feedback

---

geonode_mapstore_client/client/js/plugins/ResourceDetails/ResourceDetails.jsx
geonode_mapstore_client/client/js/plugins/ResourceDetails/components/DetailsToolbar.jsx
geonode_mapstore_client/client/js/plugins/ResourceDetails/containers/DetailsPanel.jsx
geonode_mapstore_client/static/mapstore/configs/localConfig.json

This PR adds a configurable view resource button in the detail panel

Configurable view resource button in the detail panel

---

geonode_mapstore_client/client/js/epics/gnresource.js
geonode_mapstore_client/client/js/epics/gnsave.js
geonode_mapstore_client/client/js/selectors/resource.js

This PR enhances the pending state handler for dataset resource type to capture also create new style change

Enhance pending state handler for dataset

---

geonode_mapstore_client/client/js/api/geonode/v2/metadata.js

This PR fixes view metadata menu getting disabled even when no metadata is modified
- #1973

Fix - View metadata menu is disabled when no metadata is updated

---

geonode_mapstore_client/client/js/plugins/ResourceDetails/components/DetailsToolbar.jsx
geonode_mapstore_client/client/js/plugins/Share.jsx
geonode_mapstore_client/client/js/utils/ResourceUtils.js

This PR updates share url to return uuid url

Update Share URL return UUID URL

---

geonode_mapstore_client/client/js/utils/PluginsContextUtils.js

This PR updates point of contract link to profile page

Update point of contact href to profile page

---

geonode_mapstore_client/client/js/components/enhancers/withScrollableTabs.jsx
geonode_mapstore_client/client/js/plugins/ResourceDetails/containers/DetailsPanel.jsx
geonode_mapstore_client/client/themes/geonode/less/_base.less

This PR implements scrollable tabs
https://github.com/user-attachments/assets/b5460f24-8850-4ed4-b3e1-bd5c36fb8d23

Implement scrollable tabs

---

geonode_mapstore_client/static/mapstore/configs/localConfig.json

This PR updates MS submodule to latest 2025.01.xx to include LayerDownload updates

Include the new LayerDownload in GeoNode client

---

geonode_mapstore_client/static/mapstore/configs/localConfig.json

This PR fixes the empty view menu when mapviewer is connected to a map
https://github.com/user-attachments/assets/e58a1766-f4ec-4719-844f-3f65cea89f22
- #2135

#2135: Fix - View menu is hidden when a mapviewer is connected to a map

---

geonode_mapstore_client/client/js/plugins/MetadataEditor/components/_templates/ArrayFieldItemTemplate.jsx
geonode_mapstore_client/client/js/plugins/MetadataEditor/components/_templates/index.js
geonode_mapstore_client/client/themes/geonode/less/_metadata.less

This PR updates array fields toolbar button positioning

Improve trash and order button positioning for nested fields
