geonode_mapstore_client/client/themes/default/less/geonode.less, geonode_mapstore_client/client/themes/preview/less/geonode.less, geonode_mapstore_client/static/geonode/js/ms2/utils/ms2_base_plugins.js, geonode_mapstore_client/templates/geonode-mapstore-client/base_ms.html
This PR fixes the position of print dialog in the map and layer preview pages
=> Fix positioning of MapStore Print dialog inside map/layer preview

geonode_mapstore_client/client/package.json, geonode_mapstore_client/client/webpack.config.js
This PR changes the local environment to develop without a local instance of GeoNode but instead to take advantage of an external dev instance using the webpack devServer proxy.
Here some other suggestions to improve the dev environment (these probably need further investigation):
- if possible avoid absolute urls in the `defaultConfig`
```js
// eg:
// current
proxy: "http://my-geonode.org/proxy/?url="
// expected
proxy: "/proxy/?url="
```
- centralize all the injected variable of the template in a single object (currently they are injected in different part of the `initMapStore2API` script)
```js
// eg
window.geonode_config = {
geoserver: "{{ OGC_SERVER.default.PUBLIC_LOCATION|default:"" }}",
token: "{{ ACCESS_TOKEN }}",
locale: "{{ LANGUAGE_CODE }}"
...
};
```
- externalize all …
=> Introduce the support for local development with remote host

geonode_mapstore_client/static/geonode/js/ms2/utils/ms2_composer_plugins.js
This PR enable the add group plugin in the Map editor:
=> Enable add group plugin in the map editor

geonode_mapstore_client/static/geonode/js/ms2/utils/ms2_map_viewer_plugins.js, geonode_mapstore_client/static/geonode/js/ms2/utils/ms2_viewer_plugins.js
The current SearchServicesConfig plugin is a bit confusing in the GeoNode context.
This PR removes this from the configuration but keeps the plugin available in the js bundle.
=> Remove the geocoding configuration from Mapstore client 

mapstore2_adapter/plugins/geonode.py
Adds a check of permissions and read-only mode on canEdit and canDelete configurations
=> [Fixes #93] Editing is not disabled when in Read-Only mode

mapstore2_adapter/plugins/geonode.py
Adds a check of permissions and read-only mode on canEdit and canDelete configurations
=> [Fixes #93] Editing is not disabled when in Read-Only mode #94

mapstore2_adapter/plugins/geonode.py
Adds a check of permissions and read-only mode on canEdit and canDelete configurations
=> [Backport 2.1.x ] Editing is not disabled when in Read-Only mode

geonode_mapstore_client/apps.py, geonode_mapstore_client/client/js/actions/gnviewer.js, geonode_mapstore_client/client/js/api/geonode/config/index.js, geonode_mapstore_client/client/js/api/geonode/v2/index.js, geonode_mapstore_client/client/js/apps/gn-viewer.js, geonode_mapstore_client/client/js/components/home/DetailsPanel.jsx, geonode_mapstore_client/client/js/epics/gnviewer.js, geonode_mapstore_client/client/js/hooks/usePluginItems.js, geonode_mapstore_client/client/js/plugins/ActionNavbar.jsx, geonode_mapstore_client/client/js/plugins/BrandNavbar.jsx, geonode_mapstore_client/client/js/plugins/EditorLayout.jsx, geonode_mapstore_client/client/js/plugins/ViewerLayout.jsx, geonode_mapstore_client/client/js/plugins/index.js, geonode_mapstore_client/client/js/routes/DocumentViewer.jsx, geonode_mapstore_client/client/js/routes/GeoStoryViewer.jsx, geonode_mapstore_client/client/js/routes/LayerViewer.jsx, geonode_mapstore_client/client/js/routes/MapViewer.jsx, geonode_mapstore_client/client/js/utils/GNSearchUtils.js, geonode_mapstore_client/client/static/mapstore/configs/geostory.json, geonode_mapstore_client/client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/client/static/mapstore/configs/map.json, geonode_mapstore_client/client/themes/default/less/geonode.less, geonode_mapstore_client/templates/geonode-mapstore-client/viewer.html
This PR introduces the basic wireframe structure for the viewers using an SPA and the GeoNode API V2.
The new paths are:
- `/viewer/#/document/:pk` viewer or editor with general functionalities for document resource
- `/viewer/#/layer/:pk` viewer or editor with general functionalities for layer resource
- `/viewer/#/layer/:pk/edit/data/` specific editor for layer attributes
- `/viewer/#/layer/:pk/edit/style/` specific editor for layer styles
- `/viewer/#/map/:pk` viewer or editor with general functionalities for map resource
- `/viewer/#/geostory/:pk` viewer or editor with general functionalities for geostory app resource
This viewers are working with a new bundle called gn-viewer.
Currently the paths are connected to the homepage through the detail panel only in development environment.
=> Implement client viewers architecture

geonode_mapstore_client/client/js/components/home/ResourceCard.jsx, geonode_mapstore_client/client/themes/geonode/scss/_resource-card.scss
There was a regression on text overflow on resource cards when they were in grid layout and this PR fixes it
=> Fix text overflow for resources cards in grid layout 

geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html
Changes `__GEONODE_CONFIG__.permissionsList` to `__GEONODE_CONFIG__.perms`
=> [Backport 2.1.x][Fixes #135] Refactor how resource permissions are set inside the mapstore client context

mapstore2_adapter/geoapps/geostories/api/serializers.py, mapstore2_adapter/geoapps/geostories/api/urls.py
=> [Fixes #168] Responses do not include URLs for each resource in GeoNode v2 api for geostories

geonode_mapstore_client/templates/geonode-mapstore-client/app/geostory.html, geonode_mapstore_client/templates/geonode-mapstore-client/layer_embed.html, geonode_mapstore_client/templates/geonode-mapstore-client/map_edit.html, geonode_mapstore_client/templates/geonode-mapstore-client/map_embed.html, geonode_mapstore_client/templatetags/client_version.py
=> [Backport 2.1.x] [Fixes #189]: A hash is needed for gn-xxx.js links otherwise browsers load stale code

mapstore2_adapter/geoapps/geostories/api/serializers.py, mapstore2_adapter/geoapps/geostories/api/urls.py
=> [Backport 2.1.x] [Fixes #168] Responses do not include URLs for each resource in GeoNode v2 api for geostories 

geonode_mapstore_client/client/js/epics/__tests__/gnviewer-test.js, geonode_mapstore_client/client/js/epics/gnviewer.js
Expected result:
- empty geostory is loaded and the geostory mode is set to edit
Current result:
- the empty geostory page is visible
=> Client - Create new geostory does not show an empty story

geonode_mapstore_client/client/js/plugins/SaveAs.jsx
Change the "Save As" button inside the save as window to "Save"
Result in PR:
=> Client - Change the "Save As" button inside the save as window to "Save"

geonode_mapstore_client/client/js/api/geonode/v2/index.js, geonode_mapstore_client/client/js/components/ActionNavbar/ActionNavbar.jsx, geonode_mapstore_client/client/js/components/Menu/DropdownList.jsx, geonode_mapstore_client/client/js/components/Menu/MenuItem.js, geonode_mapstore_client/client/themes/geonode/less/_action-navbar.less, geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html, geonode_mapstore_client/templatetags/get_menu_json.py
This PR allows the user to create four different menu placeholders that will populate the targeted menu with the custom items configured in the admin panel. The placeholder are:
- TOPBAR_MENU - Main menu on the left side
- TOP_MENUBAR_LEFT - Main menu on the left side
- TOP_MENUBAR_RIGHT - Main menu on the right side
- CARDS_MENU - Menu of the list of resources cards (near sort button)
=> Populate clients menus from menus models

geonode_mapstore_client/client/js/components/ContentsEditable/ThumbnailEditable.jsx, geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json, geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json, geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json, geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json, geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json, geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
Currently only a semitransparent "upload" icon is visible on top of the thumbnail of the detail panel. A textual hint saying something like "change thumbnail" or "upload a new thumbnail" should be either shown on hover or under the icon.
Result in PR:
https://user-images.githubusercontent.com/4085786/123806736-82e8a480-d8ef-11eb-8878-006dad457003.mov
=> Add hint on hover for the thumbnail editing inside the detail panel

geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
Share icon button and View ... have some misalignment that is visible on hover.
Result in PR:
=> Fix padding of detail / preview panel button

geonode_mapstore_client/client/js/components/home/DetailsPanel.jsx, geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
The should sit to the right of the text, otherwise it's not clear what thei serve for.
Result in PR:
=> Improve the positioning of the edit icons inside detail panel

geonode_mapstore_client/apps.py, mapstore2_adapter/api/urls.py
It clears this:
It also fixes duplicate URLs, as we see for `mapstore/rest/`. 
Before it was:
Now it is:
=> [FIXES #344] rest_framework namespace and duplicate URLs

geonode_mapstore_client/apps.py, mapstore2_adapter/api/urls.py
It clears this:
It also fixes duplicate URLs, as we see for `mapstore/rest/`. 
Before it was:
Now it is:
=> [FIXES #344] Real Cause of 'rest_framework namespace is not Unique' is not Fixed

geonode_mapstore_client/client/js/utils/ResourceUtils.js
The share panel did not show correctly names and images of entries after close/open interaction. This PR fixes the behaviour
=> Ensure information of permissions entries are always visible

geonode_mapstore_client/client/js/components/FiltersForm/FiltersForm.jsx, geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json, geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json, geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json, geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json, geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json, geonode_mapstore_client/templates/geonode-mapstore-client/snippets/search_bar.html
Currently the count of filter is misleading when using the search input in the top navbar. This PR adds an input text to filter form to keep highlight the current query text
=> Add search input to filter form

README.md
in PR:
- add documentation in the read me on how to extend the configuration for a plugin and link specific configuration of MapStore framework
- verify configurability of Search plugin in a custom geonode-project
=> [Doumentation] Verify extensibility of Search plugin services configuration

geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx, geonode_mapstore_client/client/js/plugins/FitBounds.jsx, geonode_mapstore_client/client/js/utils/ResourceUtils.js, geonode_mapstore_client/client/themes/geonode/less/ms-theme.less
This PR fixes following issues:
- use the detail_url from the resource object instead of create it client side
- ensure that the fit bounds does not exceed the max extent of web mercator
- fix a minor style issue on date filter of attribute table
=> Use the detail_url from the resource object

geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx, geonode_mapstore_client/client/themes/geonode/less/_menu.less
This PR introduce these points:
- do not show the label in case no filters are applied
- remove the background color of the badge
- add a bit of spacing between the sentences, the separator and the trash icon
- increase a bit the size of the trash icon.
=> Improvements to label with numbers of filters applied

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
This PR introduces a data value check: If a key as empty or None values the key will be hidden, in the detail panel definition list
=> Hide empty fields from the info tab

geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx, geonode_mapstore_client/client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/client/themes/geonode/less/_resource-card.less
This PR introduces:
- a "View" button for the card when in "grid mode" that will open the editor
- Rename the "Open" label inside the "list mode" card menu to Vi
ew
=> Add button to directly open the resource editor

geonode_mapstore_client/client/js/actions/visualstyleeditor.js, geonode_mapstore_client/client/js/apps/gn-map.js, geonode_mapstore_client/client/js/epics/gnresource.js, geonode_mapstore_client/client/js/epics/visualstyleeditor.js, geonode_mapstore_client/client/js/plugins/VisualStyleEditor.jsx, geonode_mapstore_client/client/js/plugins/index.js, geonode_mapstore_client/client/js/utils/ResourceUtils.js, geonode_mapstore_client/client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json, geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json, geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json, geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json, geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json, geonode_mapstore_client/client/themes/geonode/less/_visual-style-editor.less, geonode_mapstore_client/client/themes/geonode/less/geonode.less, geonode_mapstore_client/client/themes/geonode/less/ms-theme.less
This PR introduces a new custom plugin called VisualStyleEditor that makes use of framework components of the MapStore style editor. This plugin fits inside the dataset edit style page.
=> Adapt style editor component to fit inside the dataset style editor page

geonode_mapstore_client/client/js/apps/gn-dashboard.js, geonode_mapstore_client/client/js/hooks/useLazyPlugins.js, geonode_mapstore_client/client/js/plugins/index.js, geonode_mapstore_client/client/js/routes/Dashboard.jsx, geonode_mapstore_client/client/js/routes/GeoStory.jsx, geonode_mapstore_client/client/js/routes/MapView.jsx, geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
This PR updates the MapStore2 submodule including following fixes:
- #573 Downloading a layer with quick filter causes an error
- https://github.com/GeoNode/geonode/issues/8324
There are also improvement backported from master to optimize plugin loading and improvement to dashboard app to apply correct interactions at startup
- #584 Interactions between widgets stop working after saving a dashboard
=> Update submodule to latest 2021.02.xx and dashboard app initialization

geonode_mapstore_client/client/js/plugins/actionnavbar/buttons.jsx
This PR fixes this behavior #598 the components in overlay are visible
=> #598: Fullscreen does not work for portals

geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx, geonode_mapstore_client/client/js/routes/Detail.jsx, geonode_mapstore_client/client/js/routes/Home.jsx, geonode_mapstore_client/client/js/routes/Search.jsx
This PR introduces the loading spinner in the filter menu:
https://user-images.githubusercontent.com/4085786/142893885-f7945fc1-090f-4abe-bf6c-9e493bdda0fe.mov
=> Add loading spinner beside the "# resources found"

geonode_mapstore_client/client/js/components/Menu/Menu.js, geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
`Create New` button is now `primary` variant. 
Dropdown list items have been grouped in "upload" and "create".
=>  Make "Create new" a primary button and reorder menu items

geonode_mapstore_client/client/js/components/ActionNavbar/ActionNavbar.jsx, geonode_mapstore_client/client/js/components/ActionNavbar/__test__/ActionNavbar-test.jsx, geonode_mapstore_client/client/js/plugins/ActionNavbar.jsx, geonode_mapstore_client/client/js/plugins/DatasetsCatalog.jsx, geonode_mapstore_client/client/js/plugins/DetailViewer.jsx, geonode_mapstore_client/client/js/routes/Viewer.jsx, geonode_mapstore_client/client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/client/themes/geonode/less/_menu.less, geonode_mapstore_client/client/themes/geonode/less/_variables.less
This PR introduces the following in editor page:
- A class added by the MapStore client to force the navigation bar hidden
- A reduction in the size of the action bar
- A compact breadcrumb with a "home" icon linking to the catalogue home
- The resource title, which is cut (with ellipsis) and a title which shows the full content moved to the left
- An "i" icon which replaces the "Info" button
=> UI improvements to the toolbars for the editor page

geonode_mapstore_client/client/js/epics/gnresource.js
This PR introduces a `_v_` parameter to force a cache drop when querying for layers after styles have been applied.
=>  Force layer update when the style editor is closed

geonode_mapstore_client/client/js/epics/index.js, geonode_mapstore_client/client/js/plugins/LayerSettings.jsx, geonode_mapstore_client/client/js/plugins/__tests__/LayerSettings-test.jsx, geonode_mapstore_client/client/js/plugins/index.js, geonode_mapstore_client/client/js/plugins/layersettings/BaseLayerSettings.jsx, geonode_mapstore_client/client/js/plugins/layersettings/GeneralSettings.jsx, geonode_mapstore_client/client/js/plugins/layersettings/GroupSettings.jsx, geonode_mapstore_client/client/js/plugins/layersettings/SettingsSection.jsx, geonode_mapstore_client/client/js/plugins/layersettings/VisibilitySettings.jsx, geonode_mapstore_client/client/js/plugins/layersettings/WMSLayerSettings.jsx, geonode_mapstore_client/client/js/plugins/layersettings/_tests_/BaseLayerSettings-test.jsx, geonode_mapstore_client/client/js/plugins/layersettings/_tests_/GeneralSettings-test.jsx, geonode_mapstore_client/client/js/plugins/layersettings/_tests_/GroupSettings-test.jsx, geonode_mapstore_client/client/js/plugins/layersettings/_tests_/SettingsSection-test.jsx, geonode_mapstore_client/client/js/plugins/layersettings/_tests_/VisibilitySettings-test.jsx, geonode_mapstore_client/client/js/plugins/layersettings/_tests_/WMSLayerSettings-test.jsx, geonode_mapstore_client/client/js/utils/__tests__/APIUtils-test.js, geonode_mapstore_client/client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json, geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json, geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json, geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json, geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json, geonode_mapstore_client/client/themes/geonode/less/_layer-settings.less, geonode_mapstore_client/client/themes/geonode/less/geonode.less
This PR introduces a new custom layer settings plugin as replacement of TOCItemSettings. The main reason is to have controls on the possible input fields that we can use inside a geonode map context.
=> Client - Layer Settings Plugin

geonode_mapstore_client/client/js/actions/gnresource.js, geonode_mapstore_client/client/js/api/geonode/v2/index.js, geonode_mapstore_client/client/js/components/ContentsEditable/ThumbnailEditable.jsx, geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx, geonode_mapstore_client/client/js/epics/__tests__/gnresource-test.js, geonode_mapstore_client/client/js/epics/gnresource.js, geonode_mapstore_client/client/js/epics/gnsave.js, geonode_mapstore_client/client/js/plugins/DetailViewer.jsx, geonode_mapstore_client/client/js/reducers/__tests__/gnresource-test.js, geonode_mapstore_client/client/js/reducers/gnresource.js, geonode_mapstore_client/client/js/selectors/__tests__/resource-test.js, geonode_mapstore_client/client/js/selectors/resource.js, geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
This PR updates the client to adopt the new set_thumbnail api. It also implements a contextual Apply button that will be visible only when the thumbnail has been changed.
=> Set thumbnail through the set_thumbnail endpoint and add Apply button

geonode_mapstore_client/client/js/actions/visualstyleeditor.js, geonode_mapstore_client/client/js/epics/visualstyleeditor.js, geonode_mapstore_client/client/js/plugins/VisualStyleEditor.jsx, geonode_mapstore_client/client/js/plugins/visualstyleeditor/TemplateSelector.jsx, geonode_mapstore_client/client/js/selectors/__tests__/resource-test.js, geonode_mapstore_client/client/js/utils/ResourceUtils.js, geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js, geonode_mapstore_client/client/package.json, geonode_mapstore_client/client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json, geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json, geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json, geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json, geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json, geonode_mapstore_client/client/themes/geonode/less/_visual-style-editor.less
=> Style Editor improvements

geonode_mapstore_client/client/js/api/geonode/style/index.js, geonode_mapstore_client/client/js/epics/gnresource.js, geonode_mapstore_client/client/js/epics/visualstyleeditor.js, geonode_mapstore_client/client/themes/geonode/less/ms-theme.less
A workflow to force the style editor in visual mode will initizialize if a style contains the msForceVisual metadata. The client will reset this metadata to an empty string to disable this functionality
=> Implement msForceVisual style metadata property to force the switch to visual mode

geonode_mapstore_client/client/js/apps/gn-catalogue.js, geonode_mapstore_client/client/js/apps/gn-dashboard.js, geonode_mapstore_client/client/js/apps/gn-geostory.js, geonode_mapstore_client/client/js/apps/gn-home.jsx, geonode_mapstore_client/client/js/apps/gn-map.js, geonode_mapstore_client/client/js/hooks/useLazyPlugins.js, geonode_mapstore_client/client/js/utils/AppUtils.js
The epics stream of the timeline where not ready in time due to an asynchronous import of the timeline plugin. This PR add all the needed epics to the app initialization to ensure the correct setup of the timeline
=> [Fixes #756] Timing issues with timeline histogram initialization

geonode_mapstore_client/client/js/routes/Viewer.jsx, geonode_mapstore_client/client/js/utils/MenuUtils.js, geonode_mapstore_client/client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/client/themes/geonode/less/_base.less, geonode_mapstore_client/templates/base.html, geonode_mapstore_client/templates/documents/document_embed.html, geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html, geonode_mapstore_client/templates/geonode-mapstore-client/catalogue.html, geonode_mapstore_client/templates/geonode-mapstore-client/dashboard_embed.html, geonode_mapstore_client/templates/geonode-mapstore-client/dataset_embed.html, geonode_mapstore_client/templates/geonode-mapstore-client/geostory_embed.html, geonode_mapstore_client/templates/geonode-mapstore-client/map_embed.html, geonode_mapstore_client/templates/index.html, geonode_mapstore_client/templates/page.html, geonode_mapstore_client/templatetags/get_menu_json.py
- a wrapper to the html pages that assign the gn-mobile class to allow customization
- recognize mobile device and apply specific configuration from local config
- document_viewer_mobile
- dataset_viewer_mobile
- map_viewer_mobile
- geostory_viewer_mobile
- dashboard_viewer_mobile
- add isMobile variable to global geonode settings
This PR does not included fixes on specific style (eg: top search bar)
=> Update mobile structure and configuration

geonode_mapstore_client/apps.py
Related to https://github.com/GeoNode/geonode/pull/8727
Default extra metadata schema added for the mapstore-client geoapps
=> Default extra metadata schema injected for Geostories and Dashboard

geonode_mapstore_client/client/js/components/FiltersForm/FilterItems.jsx, geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx, geonode_mapstore_client/client/themes/geonode/less/_filter-form.less
This PR expands sub filters by default and reduces their top and bottom margins.
- The filter button is also set to an icon on mobile and 'Filter' on desktop.
=> Set Dataset subfilter expanded by default and reduce margins

geonode_mapstore_client/client/js/api/geonode/v2/index.js, geonode_mapstore_client/client/js/routes/Viewer.jsx, geonode_mapstore_client/client/themes/geonode/less/_menu.less, geonode_mapstore_client/templates/geonode-mapstore-client/snippets/brand_navbar.html
This PR includes some improvements on the navbar with search bar on mobile.
The size of header was not computed correctly
=> Fixes related to search bar in mobile

geonode_mapstore_client/client/js/epics/gnresource.js, geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
This PR keeps consistent the state of the map if a user switches the dataset page and the resource id is the same
=> Keep the map state on dataset page if the resource id is the same

geonode_mapstore_client/client/js/components/Permissions/PermissionsRow.jsx, geonode_mapstore_client/client/js/utils/ResourceUtils.js, geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
The PR adds accommodation for new permissions labels returned by backend
=> Use the permission labels returned by the backend

geonode_mapstore_client/client/js/apps/gn-home.jsx
This PR fixes `diableIf` check for mobile settings by initializing settings for `gn-home` app
=> Remove Add resource button from home page for mobile #815

geonode_mapstore_client/client/js/epics/datasetscatalog.js, geonode_mapstore_client/client/js/epics/index.js, geonode_mapstore_client/client/js/epics/layersettings.js, geonode_mapstore_client/client/js/epics/visualstyleeditor.js, geonode_mapstore_client/client/js/plugins/DatasetsCatalog.jsx, geonode_mapstore_client/client/js/plugins/LayerSettings.jsx
This PR remove the custom map layout manager to make the layout behaviour aligned with the one from MapStore core framework
=> [Fixes #828] Flickering of map widgets while using the get feature info

geonode_mapstore_client/client/js/routes/UploadDataset.jsx, geonode_mapstore_client/client/js/routes/UploadDocument.jsx, geonode_mapstore_client/client/js/routes/upload/PendingUploadCard.jsx, geonode_mapstore_client/client/js/routes/upload/UploadContainer.jsx, geonode_mapstore_client/client/js/routes/upload/UploadListContainer.jsx, geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json, geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json, geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json, geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json, geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
This PR introduces a 'Cancel Upload' feature for datasets and documents to:
- stop single upload transfer
- stop all the upload transfers
=> Implement action to stop upload transfers

geonode_mapstore_client/client/js/routes/UploadDataset.jsx
This PR implements the removal of deleted uploads from list no matter the response from the endpoint. In cases where the removal is unsuccessful due to a failure on the server, if the upload still continues to be processed, the client will put back its respective card.
=> If a request to delete an upload fails the card must be removed from the uploads list

geonode_mapstore_client/client/js/routes/UploadDataset.jsx, geonode_mapstore_client/client/js/routes/UploadDocument.jsx, geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx, geonode_mapstore_client/client/js/routes/upload/UploadContainer.jsx, geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json, geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json, geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json, geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json, geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
This PR implements parallel upload limit to prevent users from uploading more than the allows number of files at once. A user receives relevant error messages on exceeding the `maxParallelUploads`
=> Implement a check for default upload parallelism limit on making uploads

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
PR sets Geonode as origin and maintains selected origin in geostory editing as shown below:
=> Geostory editing: investigate if it's possible to maintain the origin when switching between resource type selection

geonode_mapstore_client/client/js/plugins/SaveAs.jsx, geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Save and Save As plugins and permissions fixed as reported [here](https://github.com/GeoNode/geonode/issues/8954)
=> Unable to Create Maps, GeosStories and Dashboards

geonode_mapstore_client/client/package.json, geonode_mapstore_client/context_processors.py, geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html
This PR introduces a new `'EXTENSIONS_FOLDER_PATH'` global variable to override mapstore's default extensions folder path inside of geonode mapstore client.
This is step in solving #889 after investigation with @allyoucanmap. The other pieces of the total fix for the issue will be added in [geonode](https://github.com/GeoNode/geonode) and [mapstore-project](https://github.com/geosolutions-it/mapstore-project) repos where they belong.
=> Added global extensions folder

geonode_mapstore_client/client/js/api/geonode/v2/index.js
This PR introduces a `'store_spatial_files=true`' tag in dataset uploads.
=> The UploadDatasetForm should POST "store_spatial_files=true" when uploading

geonode_mapstore_client/client/js/plugins/Legend.jsx, geonode_mapstore_client/client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/client/themes/geonode/less/_legend.less
This PR introduces layer visibility and opacity toggles inside Legend plugin
=> Add layer visibility toggle to legend component

geonode_mapstore_client/client/js/api/geonode/v2/index.js, geonode_mapstore_client/client/js/components/SelectInfiniteScroll/SelectInfiniteScroll.jsx
This PR fixes issues with debounce in search filter
=> Issues with filters: no debounce and dropdown closing on click

geonode_mapstore_client/client/js/components/FiltersForm/FiltersForm.jsx, geonode_mapstore_client/client/js/components/FiltersForm/__tests__/FiltersForm-test.jsx, geonode_mapstore_client/client/themes/geonode/less/_filter-form.less
=> Clear filters button not well aligned and not visible

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx, geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
This PR truncates abstracts inside the details panel info box after 100 characters and appends a 'Read more' link.
=> Truncate abstract inside the metadata table inside the info box

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx, geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
This PR truncates abstracts inside the details panel info box after 100 characters and appends a 'Read more' link.
=> [Backport 4.x][Fixes #919] Truncate abstract inside the metadata table inside the info box

geonode_mapstore_client/client/js/routes/UploadDataset.jsx, geonode_mapstore_client/client/js/routes/upload/PendingUploadCard.jsx, geonode_mapstore_client/client/js/routes/upload/UploadContainer.jsx, geonode_mapstore_client/client/themes/geonode/less/_upload.less
This PR fixes the double error entries and introduces an error tooltip inside `<PendingUploadCard>`
=> Failing datasets uploads are generating double entries in the list of not processed upload

geonode_mapstore_client/client/js/epics/__tests__/gnresource-test.js, geonode_mapstore_client/client/js/epics/gnresource.js
Both info and share panels are closed (if open) on map click
=> [Fixes #946] Autoclose info panel on single click on the map

geonode_mapstore_client/client/js/epics/__tests__/gnresource-test.js, geonode_mapstore_client/client/js/epics/gnresource.js
ref #946 
Both info and share panels are closed (if open) on map click
=> [Backport 4.x][Fixes #946] Autoclose info panel on single click on the map

geonode_mapstore_client/client/js/routes/UploadDataset.jsx, geonode_mapstore_client/client/js/routes/upload/PendingUploadCard.jsx, geonode_mapstore_client/client/js/routes/upload/UploadContainer.jsx, geonode_mapstore_client/client/themes/geonode/less/_upload.less
ref #942 
This PR fixes the double error entries and introduces an error tooltip inside `<PendingUploadCard>`
=> [Backport 4.x][Fixes #942] Failing datasets uploads are generating double entries in the list of not processed upload

geonode_mapstore_client/client/js/utils/AppUtils.js
Mapstore's `setViewer` is exposed as `window.MapStoreAPI.setGetFeatureInfoViewer`
=> Expose mapstore's setViewer to allow for custom GFI panel

geonode_mapstore_client/client/js/api/geonode/user/index.js, geonode_mapstore_client/client/js/api/geonode/v2/index.js, geonode_mapstore_client/client/js/utils/APIUtils.js, geonode_mapstore_client/client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html, geonode_mapstore_client/templatetags/apikey.py
issue: [#9377](https://github.com/GeoNode/geonode/pull/9377)
PR: [#9378](https://github.com/GeoNode/geonode/pull/9378)
=> [Fixes #973] Improve LOCKDOWN_GEONODE

geonode_mapstore_client/client/js/utils/AppUtils.js
Mapstore's `setViewer` is exposed as `window.MapStoreAPI.setGetFeatureInfoViewer`
=> [Fixes #979] Expose mapstore's setViewer to allow for custom GFI panel

geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx, geonode_mapstore_client/client/themes/geonode/less/_menu.less
This PR:
- removes the "xx resource found" label while a request is ongoing
- replaces that label with a spinner
=> [Fixes 966] Provide visual feedback while loading filtered resources

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
The resource status icon has been re-positioned inside the details panel
=> [Fixes #964] info icon for not approved / not published resource shouldn't take a line

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
This PR sets permission for Annotation and Add Dataset plugins to only users with Edit permission
=> [Fixes #986] Anonymous users have an option of adding dataset and annotations to a map

geonode_mapstore_client/client/js/api/geonode/v2/index.js
This PR adds a `with_resources = 'True'` param in `getCategories` and `getRegions` queries
=> [Fixes #969] Add "with_resources" GET parameter on regions and categories endpoints

geonode_mapstore_client/client/js/epics/gnresource.js, geonode_mapstore_client/client/js/utils/ResourceUtils.js, geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json, geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json, geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json, geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json, geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
This PR applies the following enhancements:
- includes a check inside the getExtentFromResource function and return null if the bbox extent is greater of the max extent
- in a dataset viewer a warning notification is shown explaining that the provided bbox is invalid
=> [Fixes #961] Show an error if dataset as a ll_bbox_polygon is greater then the WGS84 max extent

geonode_mapstore_client/client/js/routes/UploadDataset.jsx
This PR drops support for geojson in Dataset uploads
=> [Backport 4.x][Fixes #967] Drop support for GeoJSON upload

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
The resource status icon has been re-positioned inside the details panel
=> [Backport 4.x][Fixes #964] info icon for not approved / not published resource shouldn't take a line

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
This PR sets permission for Annotation and Add Dataset plugins to only users with Edit permission
=> [Backport 4.x][Fixes #986] Anonymous users have an option of adding dataset and annotations to a map

geonode_mapstore_client/client/js/api/geonode/v2/index.js
This PR adds a `with_resources = 'True'` param in `getCategories` and `getRegions` queries
=> [Backport 4.x][Fixes #969] Add "with_resources" GET parameter on regions and categories endpoints

geonode_mapstore_client/client/js/routes/UploadDataset.jsx, geonode_mapstore_client/client/js/routes/upload/PendingUploadCard.jsx, geonode_mapstore_client/client/js/routes/upload/UploadContainer.jsx, geonode_mapstore_client/client/js/utils/ResourceUtils.js, geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js, geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json, geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json, geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json, geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json, geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
This PR includes xml and sld metadata files. Those files, if present, must have the same name as the dataset files, else cannot be uploaded
=> [Fixes 925] The upload box should accept xml and sld files along with the dataset itself

geonode_mapstore_client/client/js/epics/gnresource.js
Fixes https://github.com/GeoNode/geonode-mapstore-client/pull/1000#issuecomment-1147258437
=> [Fixes #1011] Datasets with valid bbox do not open in viewer page

geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx, geonode_mapstore_client/client/themes/geonode/less/_menu.less
This PR:
- removes the "xx resource found" label while a request is ongoing
- replaces that label with a spinner
=> [Backport 4.x][Fixes 966] Provide visual feedback while loading filtered resources

geonode_mapstore_client/client/js/routes/UploadDataset.jsx
XML and SLD are not submitted as base_file in upload
=> [Fixes #1018] The client should not submit xml or sld(if provided) as base_file in dataset uploads

geonode_mapstore_client/client/js/plugins/Share.jsx, geonode_mapstore_client/client/js/plugins/layersettings/WMSLayerSettings.jsx, geonode_mapstore_client/client/package.json, geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html
Update MapStore submodule to 2022.01.xx branch with complete support for mapbox accessToken
=> [Fixes #976] Fix missing required accessToken for MapBox background when adding a map to a geostory

geonode_mapstore_client/client/js/plugins/Share.jsx, geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json, geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json, geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json, geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json, geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json, geonode_mapstore_client/client/themes/geonode/less/_share.less
Share links have been adjusted according to https://github.com/GeoNode/geonode-mapstore-client/issues/968#issue-1232475692
ref #968
=> [Backport 4.x][Fixes #968] Adjustments to links inside Share Panel

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
The conditional check to include Dataset and Annotations pluhgin has been extended to take into account if the resource is a new map.
=> [Fixes 1028] The DatasetCatalog plugin but be enabled for a new map

geonode_mapstore_client/client/js/selectors/__tests__/resource-test.js, geonode_mapstore_client/client/js/selectors/resource.js
Share Permissions have been fixed for users belonging to groups with manage permissions for a resource.
=> [Fixes #935] Share permissions form not showing for users in groups with manage permission

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
=> [Backport 4.x][Fixes #1020] Show invalid bbox warning on the overview of the dataset

geonode_mapstore_client/client/js/selectors/__tests__/resource-test.js, geonode_mapstore_client/client/js/selectors/resource.js
Share Permissions have been fixed for users belonging to groups with manage permissions for a resource.
=> [Backport 4.x][Fixes #935] Share permissions form not showing for users in groups with manage permission

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
The conditional check to include Dataset and Annotations plugin has been extended to take into account if the resource is a new map.
=> [Backport 4.x][Fixes 1028] The DatasetCatalog plugin but be enabled for a new map

geonode_mapstore_client/context_processors.py, geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html
=> [Fixes #1064] Expose supported upload file formats as configurations

.github/workflows/3.3.x-build.yml, .github/workflows/3.3.x-test.yml, .gitmodules, geonode_mapstore_client/client/package.json, geonode_mapstore_client/client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html, mapstore2_adapter/context_processors.py
The following improvements have been made:
- extend the [content processors](https://github.com/GeoNode/geonode-mapstore-client/blob/8b371a98515782ea21da6e6b8d04e6e901721cbe/mapstore2_adapter/context_processors.py) to include the new settings.py variable (eg MAPSTORE_TIMELINE_EXPANDED to be decided in development phase)
- extend the [geoNodeSettings](https://github.com/GeoNode/geonode-mapstore-client/blob/8b371a98515782ea21da6e6b8d04e6e901721cbe/geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html#L68-L74) to make this new variable available at the localConfig level to be applied as follow
=> [Fixes #1065] Extend configs to include new timeline setting for Mapstore's Timeline plugin

geonode_mapstore_client/client/js/actions/gnresource.js, geonode_mapstore_client/client/js/epics/__tests__/gnresource-test.js, geonode_mapstore_client/client/js/epics/gnresource.js, geonode_mapstore_client/client/js/epics/gnsave.js, geonode_mapstore_client/client/js/reducers/gnsearch.js, geonode_mapstore_client/client/package.json
The catalogue state is updated after save
=> [Fixes 1038] Reload catalogue after saving a reaource

geonode_mapstore_client/client/js/plugins/Legend.jsx, geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json, geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json, geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json, geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json, geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
=> [Backport 4.x][Fixes #1072] Dataset legend must show the dataset's title instead of Geoserver's layername

geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx, geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json, geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json, geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json, geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json, geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
A "View datasets" button, which links back to the Datasets filtered view of the catalogue has been introduced for completed uploads with no `detaliUrl`
=> Show some informative message when a GPKG is imported

geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx
Spinner only keeps track of progress
=> [Backport 4.x][Fixes #1085] Spinner is missing during the upload phase

geonode_mapstore_client/client/js/api/geonode/v2/index.js, geonode_mapstore_client/client/js/routes/UploadDataset.jsx, geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx, geonode_mapstore_client/client/js/routes/upload/UploadListContainer.jsx, geonode_mapstore_client/client/js/utils/ErrorUtils.js, geonode_mapstore_client/client/js/utils/ResourceUtils.js, geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
A separate upload flow has been included in the client for Geopackages using the execution status endpoint to track their upload statuses.
=> [Backport 4.x][Fixes 1115] Upload progress for GKPG based on execution requests

geonode_mapstore_client/client/js/actions/gnresource.js, geonode_mapstore_client/client/js/api/geonode/v2/index.js, geonode_mapstore_client/client/js/components/ActionNavbar/ActionNavbar.jsx, geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx, geonode_mapstore_client/client/js/epics/favorite.js, geonode_mapstore_client/client/js/plugins/DetailViewer.jsx, geonode_mapstore_client/client/js/reducers/__tests__/gnresource-test.js, geonode_mapstore_client/client/js/reducers/gnresource.js, geonode_mapstore_client/client/js/routes/Detail.jsx
* favorites have been fixed
* Adjusted test
=> [Backport 4.x][Fixes 1114] Favorites are broken

geonode_mapstore_client/client/js/plugins/save/SaveModal.jsx
Issues with pressing enter to clone in save modal have been fixed.
=> [Backport 4.x][Fixes 1122] Issues with pressing Enter in Clone dialog

geonode_mapstore_client/client/js/actions/gnresource.js, geonode_mapstore_client/client/js/api/geonode/v2/index.js, geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx, geonode_mapstore_client/client/js/epics/favorite.js, geonode_mapstore_client/client/js/plugins/DetailViewer.jsx, geonode_mapstore_client/client/js/reducers/__tests__/gnresource-test.js, geonode_mapstore_client/client/js/reducers/gnresource.js, geonode_mapstore_client/client/js/routes/Detail.jsx
The client adopts the field in displaying which resources have been favorited in the detail panel.
=> [Fixes 1136] The client should only depend on the new favorite field in resource object

geonode_mapstore_client/client/js/actions/gndownload.js, geonode_mapstore_client/client/js/epics/__tests__/gndownload-test.js, geonode_mapstore_client/client/js/epics/gndownload.js, geonode_mapstore_client/client/js/plugins/downloads/DublinCoreDownload.jsx, geonode_mapstore_client/client/js/plugins/downloads/IsoDownload.jsx, geonode_mapstore_client/client/js/plugins/index.js, geonode_mapstore_client/client/js/reducers/__tests__/gndownload-test.js, geonode_mapstore_client/client/js/reducers/gndownload.js, geonode_mapstore_client/client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json, geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json, geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json, geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json, geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
Metadata downloads for ISO and Dublin Core have been added
=> [Fixes 1132] Metadata download

geonode_mapstore_client/client/js/plugins/Legend.jsx
This PR adds a version parameter that invalidate the cache of the legend graphic each time we navigate in a new page of dataset
=> [Fixes #1117] Layer legend is not updated

geonode_mapstore_client/client/js/epics/datasetscatalog.js, geonode_mapstore_client/client/js/epics/layersettings.js, geonode_mapstore_client/client/js/epics/visualstyleeditor.js, geonode_mapstore_client/client/js/selectors/__tests__/mapsave-test.js, geonode_mapstore_client/client/js/selectors/mapsave.js, geonode_mapstore_client/client/js/selectors/resource.js, geonode_mapstore_client/client/js/utils/LayoutUtils.js
availableStyles property was removed from the data payload, this PR reintroduced it in the saving process
=> #1168 Some issues with map layer style editing

geonode_mapstore_client/client/js/actions/gnsearch.js, geonode_mapstore_client/client/js/epics/favorite.js, geonode_mapstore_client/client/js/reducers/gnsearch.js
The total count for favorite resource is adjusted appropriately
=> [Fixes 1169] Update total when resource is removed from favorite

geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx, geonode_mapstore_client/client/js/utils/ErrorUtils.js
The error tool-tip position is moved to the left to accommodate longer error messages without being cut out
=> [Fixes 1174] Error not correctly shown error

geonode_mapstore_client/client/js/actions/gnsearch.js, geonode_mapstore_client/client/js/epics/favorite.js, geonode_mapstore_client/client/js/reducers/gnsearch.js
The total count for favorite resource is adjusted appropriately
=> [Backport 4.x][Fixes 1169] Update total when resource is removed from favorite

geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx, geonode_mapstore_client/client/js/utils/ErrorUtils.js
The error tool-tip position is moved to the left to accommodate longer error messages without being cut out 
ref #1174
=> [Fixes 1174] Error not correctly shown error (#1176)

docs/customizations/theme.html
The theme variables are defined in the root
ref #1147
=> [Backport 4.0.x][Fixes 1147] Theme override styles from customization app needs some improvement

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
Widgets are disabled when user does not have download perms
=> [Backport 4.0.x][Fixes #1144] Disable / hide the charts button if a user doesn't have enough perms on the dataset

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
A User without `download_resourcebase` and `add_resource`is no longer able to copy/clone a dataset and document.
=> [Fixes 1177] Hide copy/clone option for users without permissions

geonode_mapstore_client/client/js/components/ContentsEditable/ThumbnailEditable.jsx
The client now utilizes a `defaultThumbnailSize` setting provided in `geoNodeSettings`
=> [Fixes 1210] Configure the client to receive image properties from server

geonode_mapstore_client/client/js/api/geonode/v2/index.js, geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx, geonode_mapstore_client/client/js/components/MetadataPreview/MetadataPreview.jsx, geonode_mapstore_client/client/js/components/MetadataPreview/index.js, geonode_mapstore_client/client/js/epics/gnsearch.js, geonode_mapstore_client/client/js/utils/ResourceUtils.js, geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json, geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json, geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json, geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json, geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
The following changes have been made: 
1. When a viewer is not available for a document, a full width/height iframe is shown with a preview of the document's metadata
> ![meta](https://user-images.githubusercontent.com/42542676/196659587-2ecb488b-6d3b-438e-bf4a-1fce972aea34.gif)
2.  In the details page, the preview panel is hidden altogether in that case,
> <img width="1295" alt="Screenshot 2022-10-19 at 09 58 49" src="https://user-images.githubusercontent.com/42542676/196660444-458ecaaa-15b8-4fdc-8981-74d80367b8b9.png">
3. View Metadata button is now 'View details'
4. On the detail page, the request for details of the resource is made to the `/documents` endpoint and not `/resources`
=> [Fixes 1243] Show metadata page in Document view when preview is not available

geonode_mapstore_client/client/js/routes/upload/UploadCard.jsx, geonode_mapstore_client/client/js/routes/upload/UploadListContainer.jsx
The new detail url for imports is implemented. The client still caters for the old upload workflow until confirmation is given to remove it.
ref #1260
=> [Fixes 1260] Adapt the client to use the new detail_url in dataset import

geonode_mapstore_client/client/js/api/geonode/v2/index.js, geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx, geonode_mapstore_client/client/js/components/MetadataPreview/MetadataPreview.jsx, geonode_mapstore_client/client/js/components/MetadataPreview/index.js, geonode_mapstore_client/client/js/epics/gnsearch.js, geonode_mapstore_client/client/js/utils/ResourceUtils.js, geonode_mapstore_client/client/static/mapstore/translations/data.de-DE.json, geonode_mapstore_client/client/static/mapstore/translations/data.en-US.json, geonode_mapstore_client/client/static/mapstore/translations/data.es-ES.json, geonode_mapstore_client/client/static/mapstore/translations/data.fr-FR.json, geonode_mapstore_client/client/static/mapstore/translations/data.it-IT.json
The following changes have been made: 
1. When a viewer is not available for a document, a full width/height iframe is shown with a preview of the document's metadata
> ![meta](https://user-images.githubusercontent.com/42542676/196659587-2ecb488b-6d3b-438e-bf4a-1fce972aea34.gif)
2.  In the details page, the preview panel is hidden altogether in that case,
> <img width="1295" alt="Screenshot 2022-10-19 at 09 58 49" src="https://user-images.githubusercontent.com/42542676/196660444-458ecaaa-15b8-4fdc-8981-74d80367b8b9.png">
3. View Metadata button is now 'View details'
4. On the detail page, the request for details of the resource is made to the `/documents` endpoint and not `/resources`
=> [Backport 4.0.x][Fixes #1243] Show metadata page in Document view when preview is not available

geonode_mapstore_client/templates/geonode-mapstore-client/snippets/search_bar.html
The `metadata_only=false filter` has been added for the search bar
=> [Fixes 1291] The search box should use metadata_only=False

geonode_mapstore_client/templates/geonode-mapstore-client/snippets/search_bar.html
The `metadata_only=false filter` has been added for the search bar
=> [Backport 4.0.x][Fixes 1291] The search box should use metadata_only=False

geonode_mapstore_client/client/js/selectors/resource.js
Registered users perms are now considered
The issue was caused by [this line](https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/client/js/selectors/resource.js#L109)
`.find` returned the permissions from the first group in `user.info.groups` (which was always 'anonymous'), and so permissions for registered users were never checked.
Since anonymous users are not relevant at this case, we can exclude that group from the checks.
=> [Fixes 1307] Manage permissions on group not respected

geonode_mapstore_client/client/js/routes/UploadDataset.jsx, geonode_mapstore_client/client/js/utils/FileUtils.js
The issue was caused because when a file is changed from geojson to json, in some cases, the file type is recorded in the file metadata as `application/json` which was not recognized by the client. This PR caters for that.
=> [Fixes 1305] Unable to upload GEOJSON files with .json extention

geonode_mapstore_client/client/static/mapstore/configs/localConfig.json
The bug was caused by a default `redirectTo` prop which triggered a location change action to `'/'`
=> [Fixes 1336] Deleting resources removes applied filters

geonode_mapstore_client/client/js/plugins/SaveAs.jsx, geonode_mapstore_client/client/js/utils/ResourceUtils.js, geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
This PR improves the checks for clone and save as actions
=> [Fixes #1308] Clone option in the list view is missing on Maps for non admin users

geonode_mapstore_client/client/js/components/FiltersForm/FilterItems.jsx
This PR does the following:
1. includes parent filter when a child filter is checked
2. removes all child filters when a parent filter is unchecked since without the parent, the child filters would not work as expected
A screen recording is added below
> ![filters](https://user-images.githubusercontent.com/42542676/202744905-4a9d87ba-1498-4a08-9ea7-d01f7465c149.gif)
=> [Backport 4.0.x][Fixes #1310] Some checkbox filter combinations fail (#1312)

geonode_mapstore_client/client/js/selectors/resource.js
Registered users perms are now considered
The issue was caused by [this line](https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/client/js/selectors/resource.js#L109)
`.find` returned the permissions from the first group in `user.info.groups` (which was always 'anonymous'), and so permissions for registered users were never checked.
Since anonymous users are not relevant at this case, we can exclude that group from the checks.
=> [Backport 4.0.x][Fixes #1307] Manage permissions on group not respected (#1316)

geonode_mapstore_client/client/js/epics/gnresource.js
This PR adds a workflow to close open panels when another is open
=> [Backport 4.0.x][Fixes #1306] Annotations and add dataset form is not opened when info is showing (#1330)

geonode_mapstore_client/client/js/routes/UploadDataset.jsx, geonode_mapstore_client/client/js/utils/FileUtils.js
The issue was caused because when a file is changed from geojson to json, in some cases, the file type is recorded in the file metadata as `application/json` which was not recognized by the client. This PR caters for that.
=> [Backport 4.0.x][Fixes #1305] Unable to upload GEOJSON files with .json extention (#1317)

geonode_mapstore_client/static/mapstore/configs/localConfig.json
#1386
This PR includes following changes:
- update MapStore2 submodule to latest 2022.02.xx commits
- add configuration to localConfig.json to hide the service selector in layer download
=> [Fixes #1386] Export service selection should be hidden

geonode_mapstore_client/client/js/components/MediaViewer/Scene3DViewer.jsx, geonode_mapstore_client/client/package.json
This PR updates the dependencies to avoid warning while compiling the client bundle
=> [Fix #1401] @react-three/drei and @react-three/fiber dependencies are throwing warning while compiling

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx
A suggestion to let the user copy the UUID-Link of a resource, instead of the detail url. Along with the UUID-resolver (see [geonode PR here](https://github.com/GeoNode/geonode/pull/10375)) the target will resolve to the detail url anyways, but gives the user the UUID-Link at hand.
=> Feature/copy UUID link to clipboard

geonode_mapstore_client/client/js/routes/Detail.jsx
#1397
This PR adds the key to the detail component to remount it every time the resource change, in this way the title will update correctly
=> [Backport 4.0.x][Fix #1397] Resource title is not visible inside the preview panel

geonode_mapstore_client/client/js/components/Accordion/Accordion.jsx, geonode_mapstore_client/client/js/components/Accordion/index.js, geonode_mapstore_client/client/js/components/FiltersForm/FilterItems.jsx, geonode_mapstore_client/client/js/components/FiltersForm/__tests__/FilterItems-test.jsx, geonode_mapstore_client/client/js/components/__tests__/Accordion-test.jsx, geonode_mapstore_client/client/themes/geonode/less/_filter-form.less, geonode_mapstore_client/client/themes/geonode/less/_variables.less
This PR adds a possibility to add accordion to filter panel with both facet or checkbox (default) style filter items
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?** (check one with "x", remove the others)
- #1410 
```
{
filtersFormItems: [
{
"id": "categories",
"type": "accordion",
"labelId": "gnviewer.categories",
"items": [
{
"id": "water",
"type": "filter",
"style": "facet", // checkbox
"labelId": "gnviewer.water",
"count": 10
}
]
}
]
}
```
**Example**
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
=> #1410: Accordion/facet type option for filter form panel

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsAttributeTable.jsx, geonode_mapstore_client/client/js/components/DetailsPanel/DetailsInfo.jsx, geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx, geonode_mapstore_client/client/js/epics/gnsearch.js, geonode_mapstore_client/client/js/utils/AppUtils.js, geonode_mapstore_client/client/themes/geonode/less/_details-panel.less, geonode_mapstore_client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json
This PR brings back the attribute table as a tab next to the info fields tab in the DetailsViewer. The PR is meant (for now) to gather feedback and improvement ideas from @giohappy @gannebamm @mattiagiupponi. 
The following issues are pointing to the missing attribute table in the DetailsViewer:
* https://github.com/GeoNode/geonode/issues/10693
* https://github.com/GeoNode/geonode/issues/10378#issuecomment-1352778569
To bring back the attribute table and put it next to the details info fields, I introduced the new `attribute_table` type and extended the `DetailsInfo` Component to either render the info fields or the attribute table:
https://github.com/Thuenen-52North-Erweiterung-GeoNode/geonode-mapstore-client/blob/8f48fae71eb5c340c448cfc31814a02fd8e5c92d/geonode_mapstore_client/client/js/ …
=> Bring back the attribute table to the DetailsViewer

geonode_mapstore_client/client/js/api/geonode/v2/index.js, geonode_mapstore_client/client/js/components/Accordion/Accordion.jsx, geonode_mapstore_client/client/js/components/ActionButtons/ActionButtons.jsx, geonode_mapstore_client/client/js/components/FiltersForm/DateRangeFilter.jsx, geonode_mapstore_client/client/js/components/FiltersForm/FilterByExtent.jsx, geonode_mapstore_client/client/js/components/FiltersForm/FilterItems.jsx, geonode_mapstore_client/client/js/components/FiltersForm/FiltersForm.jsx, geonode_mapstore_client/client/js/components/FiltersForm/__tests__/FilterItems-test.jsx, geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx, geonode_mapstore_client/client/js/components/Menu/Menu.js, geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx, geonode_mapstore_client/client/js/plugins/save/SaveModal.jsx, geonode_mapstore_client/client/js/utils/AppUtils.js, geonode_mapstore_client/client/js/utils/SearchUtils.js, geonode_mapstore_client/client/js/utils/__tests__/SearchUtils-test.js, geonode_mapstore_client/client/themes/geonode/less/_filter-form.less, geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json, geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json, geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json, geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
- add the `date-range` type to filter items
- add extent and search input to filter items
- review some configuration of select and filter for the facets
- refactor of FilterItems component to apply correctly the keys to components
- replace Message Component with getMessageById in FilterItems to apply to select options and avoid warning in particular for facets
=>  Fix #1447 Implement date filtering

geonode_mapstore_client/static/mapstore/configs/localConfig.json
This PR remove duplicated configuration for the format inside the Print plugin
=> Fix #1462 The Format option on the Print tool is present twice

geonode_mapstore_client/static/mapstore/configs/localConfig.json
This PR remove duplicated configuration for the format inside the Print plugin
=> [Backport 4.1.x] Fix #1462 The Format option on the Print tool is present twice (#1463)

geonode_mapstore_client/client/js/routes/UploadDataset.jsx
This PR reorders supported datasets format
- https://github.com/GeoNode/geonode-mapstore-client/issues/1480#issuecomment-1610173198
=> #1480: Order supported datasets format

geonode_mapstore_client/client/js/actions/gnsearch.js, geonode_mapstore_client/client/js/api/geonode/v2/index.js, geonode_mapstore_client/client/js/components/Accordion/Accordion.jsx, geonode_mapstore_client/client/js/components/DetailsPanel/DetailsInfo.jsx, geonode_mapstore_client/client/js/components/FiltersForm/FilterItems.jsx, geonode_mapstore_client/client/js/components/FiltersForm/FiltersForm.jsx, geonode_mapstore_client/client/js/components/FiltersForm/__tests__/FilterItems-test.jsx, geonode_mapstore_client/client/js/epics/__tests__/gnsearch-test.js, geonode_mapstore_client/client/js/epics/gnsearch.js, geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx, geonode_mapstore_client/client/js/reducers/gnsearch.js, geonode_mapstore_client/client/js/utils/SearchUtils.js, geonode_mapstore_client/client/js/utils/__tests__/SearchUtils-test.js, geonode_mapstore_client/client/themes/geonode/less/_filter-form.less
This PR implements the following
- https://github.com/GeoNode/geonode-mapstore-client/issues/1493 and 
- https://github.com/GeoNode/geonode-mapstore-client/issues/1494
=> #1493: Improve faceting and add facet filtering

geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
This PR updates style of detail panel to fix region field's misalignment
- #1514
=> #1514: Info panel region style fix

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsInfo.jsx, geonode_mapstore_client/client/js/components/FiltersForm/FilterItems.jsx, geonode_mapstore_client/client/js/components/Tabs/Tabs.jsx, geonode_mapstore_client/client/js/components/Tabs/index.js, geonode_mapstore_client/client/themes/geonode/less/_filter-form.less
This issue adds support to filter form to add `tabs` type
- #1500 
Sample
```JSON
{
"filtersFormItems": [
{
"id": "filter-tabs",
"type": "tabs",
"items": [
{
"id": "themes",
"type": "tab",
"labelId": "gnviewer.themes",
"items": []
},
{
"id": "projects",
"type": "tab",
"labelId": "gnviewer.projects",
"items": []
},
{
"id": "advanced",
"type": "tab",
"labelId": "gnviewer.advanced",
"items": []
}
]
}
]
}
```
=> #1500: Tabs type on filter forms

geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx, geonode_mapstore_client/client/themes/geonode/less/_resource-card.less
This PR makes the resource card to use available space to display abstract text especially in list mode. This is achieved by programatically adding ellipsis when more lines of text present.
- #1482
=> #1482: Use the available height for the abstract text in a card

geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx, geonode_mapstore_client/client/themes/geonode/less/_resource-card.less
#1482: Use the available height for the abstract text in a card (#1524)
=> [Backport 4.1.x] #1482: Use the available height for the abstract text in a card (#1524)

geonode_mapstore_client/client/js/plugins/DetailViewer.jsx
This PR fixes the `Rendered fewer hooks than expected` exception
- #1544
=> #1544: Fix - Create Map action triggers client error

geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html, geonode_mapstore_client/templates/geonode-mapstore-client/snippets/search_bar.html
With this PR we want to add:
- additional block tag in the django template
- Let the `_geonode_config.html` being overridable by geonode-project itself
=> Add override settings block

geonode_mapstore_client/client/js/utils/APIUtils.js
This PR adds `sort` to params serializer for correct params formulation ultimately fixing sorting issue
=> #1551: Sort param serializer fix

geonode_mapstore_client/client/themes/geonode/less/_menu.less, geonode_mapstore_client/static/mapstore/configs/localConfig.json
=> #1557: Remove info variant on DetailViewer button

geonode_mapstore_client/client/js/epics/gnsave.js, geonode_mapstore_client/client/js/utils/CoordinatesUtils.js, geonode_mapstore_client/client/js/utils/ResourceUtils.js, geonode_mapstore_client/client/js/utils/__tests__/CoordinatesUtils-test.js, geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js
This PR removes remove any reference to `ll_bbox_polygon` and `bbox_polygon` and updates the client to use `extent` for read and `bbox` to write
- #1562
=> #1562: Adopt extent property for resources

geonode_mapstore_client/templatetags/get_menu_json.py
The user menu includes a link pointing to `/geoserver` for logged in admins. However, it always should point to the public Web UI using `settings.GEOSERVER_WEB_UI_LOCATION` setting.
=> Point to geoserver public UI

geonode_mapstore_client/client/js/actions/gnresource.js, geonode_mapstore_client/client/js/components/DetailsPanel/DetailsInfo.jsx, geonode_mapstore_client/client/js/components/DetailsPanel/DetailsLocations.jsx, geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx, geonode_mapstore_client/client/js/components/DrawExtent/DrawExtent.jsx, geonode_mapstore_client/client/js/components/DrawExtent/index.js, geonode_mapstore_client/client/js/components/Tabs/Tabs.jsx, geonode_mapstore_client/client/js/components/ZoomTo/ZoomTo.jsx, geonode_mapstore_client/client/js/epics/gnsave.js, geonode_mapstore_client/client/js/plugins/DetailViewer.jsx, geonode_mapstore_client/client/js/reducers/gnresource.js, geonode_mapstore_client/client/js/selectors/resource.js, geonode_mapstore_client/client/js/utils/ResourceUtils.js, geonode_mapstore_client/client/js/utils/__tests__/ResourceUtils-test.js, geonode_mapstore_client/client/themes/geonode/less/_details-panel.less, geonode_mapstore_client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json, geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json, geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json, geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
This PR adds spatial extent visualization and management to details viewer panel
- #1539 
_Note_: I couldn't match the marker in issue with the ones supported by MS. Kindly let me know if this needs to be modified
**View**
<kbd>
</kbd>
**Edit**
<kbd>
</kbd>
=> #1539: Spatial extent visualization and management

geonode_mapstore_client/client/js/epics/gnresource.js, geonode_mapstore_client/client/js/plugins/FitBounds.jsx
This PR fixes the zoom not preserved when saving a map created from a dataset
- #1573
=> #1573: Fix - Map save doesn't preserve zoom when created from a dataset

geonode_mapstore_client/client/js/api/geonode/v2/index.js, geonode_mapstore_client/client/js/components/DetailsPanel/DetailsLinkedResources.jsx, geonode_mapstore_client/client/js/epics/__tests__/detailviewer-test.js, geonode_mapstore_client/client/js/epics/detailviewer.js, geonode_mapstore_client/client/themes/geonode/less/_details-panel.less, geonode_mapstore_client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json, geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json, geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json, geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
This PR updated linked resources tab with `linked_by` and `linked_to` fields and remove deprecated `resources` prop
- #1584
=> #1584: Linked resources refer to new properties

geonode_mapstore_client/client/js/plugins/DownloadResource.jsx
This PR fixes the download button visibility with `download_urls` present and with `view` only perms
- #1603
=> #1603: Fix - Download button visibility with url and view only perms

geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx, geonode_mapstore_client/client/js/components/MediaViewer/PdfViewer.jsx
This PR fixes the pdf preview in the viewer. It uses `embed_url` when available for PDF viewer
- #1619
=> #1619: Fix - Preview remote document in iframe

geonode_mapstore_client/static/mapstore/configs/localConfig.json
This PR enables search service config plugin for maps (map_viewer and dataset_viewer)
- #1621
=> #1621: Implement search service configuration for Maps

geonode_mapstore_client/client/js/plugins/Share.jsx, geonode_mapstore_client/client/js/selectors/__tests__/resource-test.js, geonode_mapstore_client/client/js/selectors/resource.js
This PR fixes the share manage resource permission by checking `perms` array of the resource instead of the `/permissions` api response
- #1635
=> #1635: Share option is available only to user with manage permissions

geonode_mapstore_client/client/js/components/MediaViewer/PdfViewer.jsx, geonode_mapstore_client/client/js/utils/APIUtils.js, geonode_mapstore_client/client/js/utils/FileUtils.js, geonode_mapstore_client/client/js/utils/ResourceUtils.js
It is not possible to prevent the popup download If a remote PDF responds with Content-Disposition that triggers it and to fix this behaviour we are introducing following changes:
- remote documents will not be previewed in the catalogue detail panel. We will show the thumbnail or the default icon.
- for all pdf files we will perform a direct request followed by a proxy request only in case the first fails. If both fails we will show the metadata preview
=> #1627 Review remote pdf preview

geonode_mapstore_client/client/js/components/MediaViewer/PdfViewer.jsx, geonode_mapstore_client/client/js/utils/FileUtils.js, geonode_mapstore_client/client/js/utils/ResourceUtils.js
It is not possible to prevent the popup download If a remote PDF responds with Content-Disposition that triggers it and to fix this behaviour we are introducing following changes:
- remote documents will not be previewed in the catalogue detail panel. We will show the thumbnail or the default icon.
- for all pdf files we will perform a direct request followed by a proxy request only in case the first fails. If both fails we will show the metadata preview
=> [Backport 4.2.x] #1627 Review remote pdf preview (#1642)

geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx, geonode_mapstore_client/client/js/components/ResourceCard/ResourceCard.jsx, geonode_mapstore_client/client/js/components/Unadvertised/Unadvertised.jsx, geonode_mapstore_client/client/js/components/Unadvertised/index.js, geonode_mapstore_client/client/themes/geonode/less/_details-panel.less, geonode_mapstore_client/client/themes/geonode/less/_resource-card.less, geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json, geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json, geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json, geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
This PR adds an identifier to unadvertised resources in the resource grid, detail panel (viewer & preview) along with tooltip
- #1657 
<kbd>
</kbd>
<kbd>
</kbd>
<kbd>
</kbd>
=> #1657 - Add unadvertised identifier to the resource

geonode_mapstore_client/client/js/routes/Viewer.jsx, geonode_mapstore_client/client/themes/geonode/less/ms-theme.less
When the user extension plugin is employed with user plugins lazy loaded, the viewer makes unwanted requests to fetch resource configuration and loading of the viewer page when the user plugin is activated after loaded.
This PR enhances the viewer plugin loading and prevents unwanted requesting resource configurations when the user extension plugin is employed.
=> User extension plugin invocation improvement

geonode_mapstore_client/client/js/actions/gnresource.js, geonode_mapstore_client/client/js/api/geonode/v2/index.js, geonode_mapstore_client/client/js/components/ResourcesCompactCatalog/ResourcesCompactCatalog.jsx, geonode_mapstore_client/client/js/epics/gnresource.js, geonode_mapstore_client/client/js/epics/gnsave.js, geonode_mapstore_client/client/js/epics/gnsearch.js, geonode_mapstore_client/client/js/epics/resourceservice.js, geonode_mapstore_client/client/js/plugins/MapViewerConfiguration.jsx, geonode_mapstore_client/client/js/plugins/MapViewersCatalog.jsx, geonode_mapstore_client/client/js/plugins/index.js, geonode_mapstore_client/client/js/reducers/__tests__/gnresource-test.js, geonode_mapstore_client/client/js/reducers/gnresource.js, geonode_mapstore_client/client/js/utils/ResourceServiceUtils.js, geonode_mapstore_client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/static/mapstore/configs/pluginsConfig.json, geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json, geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json, geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json, geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
This PR enhances the link system between map and map viewer
https://github.com/geosolutions-it/C130-TOTAL-2024-GeoNode-DEV/issues/4
**Create viewer and link**
https://github.com/GeoNode/geonode-mapstore-client/assets/26929983/3b162c6c-b1ed-4dda-93f7-7ceb361a9e57
**Edit viewer and back to map**
https://github.com/GeoNode/geonode-mapstore-client/assets/26929983/0cf706fc-d6e2-4050-883f-4412a077f4ae
**Delete viewer (When mapviewer is linked only this map)**
https://github.com/GeoNode/geonode-mapstore-client/assets/26929983/4442bee0-c536-4121-b5ce-6eeb3100461f
**Link viewer and remove link (when mapviewer is linked to multiple map)**
https://github.com/GeoNode/geonode-mapstore-client/assets/26929983/4e3456ca-37c9-44cf-8926-688488e59f39
=> Enhance link system between map and mapviewers

geonode_mapstore_client/client/js/plugins/index.js, geonode_mapstore_client/client/themes/geonode/less/ms-theme.less, geonode_mapstore_client/static/mapstore/configs/pluginsConfig.json, geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json, geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json, geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json, geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
This PR enhances and updates context creator plugins and configurations
`MapCatalog` - list Mapstore resources (not useful in Geonode) as we already have datasets catalog
`MapTemplate` - performs creation of templates relying on Geostore
=> Configuration update for the plugins available inside the context creator

geonode_mapstore_client/static/mapstore/configs/localConfig.json
This PR updates `map_viewer` to have GlobeSwitcher plugin
- #1683
=> #1683: Enable the 3D plugin in the default GeoNode map configuration

geonode_mapstore_client/client/js/epics/gnresource.js, geonode_mapstore_client/client/js/routes/Viewer.jsx
- This PR fixes the new map viewer loading 
- The following works fine as well
- Map load
- User plugin load
- Map viewer load
- No duplicate resource calls
- Reload map on unlink viewer resource to reset map's default plugin
- #1685
=> #1685 - Fix: Mapviewer doesn't show configure plugin steps

geonode_mapstore_client/client/js/epics/gnresource.js, geonode_mapstore_client/client/js/plugins/Save.jsx, geonode_mapstore_client/client/js/plugins/SaveAs.jsx, geonode_mapstore_client/client/js/plugins/save/withPrompt.jsx, geonode_mapstore_client/client/js/selectors/__tests__/resource-test.js, geonode_mapstore_client/client/js/selectors/resource.js
This PR adds a prompt warning to the new map viewer. Added `withPrompt` hoc and code refactored
- #1689
=> #1689: Add a warning when closing an unsaved map viewer

geonode_mapstore_client/static/mapstore/configs/pluginsConfig.json
This PR removes the selection of `LongitudinalProfileTool` plugin from map viewer
- #1695 
> [!NOTE]
> Open any viewer created with `LongitudinalProfileTool` plugin and save to update the viewer excluding the removed plugin or simply remove the viewer
=> #1695 - Remove selection of LongitudinalProfileTool plugin from map viewer

geonode_mapstore_client/apps.py, geonode_mapstore_client/client/js/api/geonode/v2/index.js, geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx, geonode_mapstore_client/client/js/epics/gnresource.js, geonode_mapstore_client/client/js/epics/index.js, geonode_mapstore_client/client/js/utils/APIUtils.js, geonode_mapstore_client/client/js/utils/FileUtils.js, geonode_mapstore_client/client/js/utils/__tests__/FileUtils-test.js
This PR adds api preset changes by aligning with master
- #1710
=> [Backport] #1710 - Update calls with catalog_list preset (#1711)

geonode_mapstore_client/client/themes/geonode/less/_layer-settings.less
This PR fixes the layer settings select dropdown are covered by titles
- #1722
=> #1722: Fix - LayerSettings select dropdown are covered by titles

geonode_mapstore_client/client/js/plugins/layersettings/WMSLayerSettings.jsx
This PR fixes the tile format select input options not being displayed
- #1726
=> #1726: Fix - Tile format select input not shown

geonode_mapstore_client/client/themes/geonode/less/ms-theme.less
This PR fixes the chart widget header's style
- #1732
=> #1732: Fix - Chart widget header style

geonode_mapstore_client/client/js/epics/__tests__/gnresource-test.js, geonode_mapstore_client/client/js/epics/datasetscatalog.js, geonode_mapstore_client/client/js/epics/gnresource.js, geonode_mapstore_client/client/js/epics/layersettings.js, geonode_mapstore_client/client/js/epics/visualstyleeditor.js, geonode_mapstore_client/static/mapstore/configs/pluginsConfig.json
This PR fixes 
- Incorrect positioning of the panels and maplayout configurations
- Closing contradicting panels
- Drawer menu default width
- #1730 
[<img width="961" alt="Screenshot 2024-04-19 at 4 11 05 PM" src="https://github.com/GeoNode/geonode-mapstore-client/assets/26929983/b7a08298-ce60-452f-b8b8-f5f7c6b947ba">](https://drive.google.com/file/d/1YNi3rbZEUtC-md1s8xZFcS5GQevNMEB1/view)
=> #1730: Fix - Incorrect positioning of panels

geonode_mapstore_client/client/js/routes/upload/UploadListContainer.jsx
This PR updates the output_params info from the execution requests for uploads
- #1748
=> #1748 - Update output_params info from the execution requests for uploads

geonode_mapstore_client/client/js/epics/gnresource.js, geonode_mapstore_client/static/mapstore/configs/localConfig.json
This PR fixes the viewer of map becomes manageable when user lacks permission to viewer but has permission of the map
- `Delete viewer` shown when user has manage permission to both map and viewer
- `Edit viewer` shown when user has edit permission to both map and viewer
- #1756
=> #1756 - Fix: Viewer of map is manageable when user lacks permission

geonode_mapstore_client/static/mapstore/configs/localConfig.json
This PR updates configuration to display resource menu properly based on user permission
=> #1762 - Fix share button not visible for users without editing permissions

geonode_mapstore_client/static/mapstore/configs/localConfig.json
This PR updated configuration of map to show catalog plugin in default map view
- #1772
=> #1772: Add MapStore catalog plugin by default for maps

geonode_mapstore_client/client/themes/geonode/less/ms-theme.less
Fixes #1782  by adding a missing chart-switcher style. 
Same way as defined in mapstore :  https://github.com/geosolutions-it/MapStore2/blob/bf8efddfe477b775699fd0eb222ed8d313f9f6c3/web/client/themes/default/less/widget.less#L343
=> Add missing chart-switcher css class

geonode_mapstore_client/client/js/plugins/ActionNavbar.jsx, geonode_mapstore_client/client/js/routes/Viewer.jsx, geonode_mapstore_client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json, geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json, geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json, geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
- Add the `All resources` button to all viewers
- Move the hidden topbar logic from the route page to the action navbar to avoid double tobbar glitch
=> Fix #1789 Add action to return back to the All resources page from a viewer

geonode_mapstore_client/client/js/plugins/ActionNavbar.jsx, geonode_mapstore_client/client/js/routes/Viewer.jsx, geonode_mapstore_client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json, geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json, geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json, geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
- Add the `All resources` button to all viewers
- Move the hidden topbar logic from the route page to the action navbar to avoid double tobbar glitch
=> [Backport 4.3.x] Fix #1789 Add action to return back to the All resources page from a viewer (#1791)

geonode_mapstore_client/client/themes/geonode/less/ms-theme.less
Fixes #1782  by adding a missing chart-switcher style. 
Same way as defined in mapstore :  https://github.com/geosolutions-it/MapStore2/blob/bf8efddfe477b775699fd0eb222ed8d313f9f6c3/web/client/themes/default/less/widget.less#L343
=> [Backport 4.3.x] Add missing chart-switcher css class (#1783)

geonode_mapstore_client/client/js/apps/gn-catalogue.js, geonode_mapstore_client/client/js/apps/gn-components.js, geonode_mapstore_client/client/js/apps/gn-dashboard.js, geonode_mapstore_client/client/js/apps/gn-document.js, geonode_mapstore_client/client/js/apps/gn-geostory.js, geonode_mapstore_client/client/js/apps/gn-map.js, geonode_mapstore_client/client/js/plugins/index.js
This storeDetailsInfoDashboardEpic introduced in latest version of mapstore should not be used by geonode because includes actions related to geostore the default MapStore backend.
This PR removes storeDetailsInfoDashboardEpic from the epic included in geonode because it's adding a not needed  request
=> Fix #1781 Request to rest/geostore in latest version when loading dashboard

geonode_mapstore_client/client/js/routes/Viewer.jsx, geonode_mapstore_client/client/js/utils/ResourceUtils.js
This PR improve the Viewer route checks to allows resource update for the same resource_type
=> Fix #1811 Dataset viewer breaks when clicking a linked dataset

geonode_mapstore_client/client/js/apps/gn-catalogue.js, geonode_mapstore_client/client/js/apps/gn-components.js, geonode_mapstore_client/client/js/apps/gn-dashboard.js, geonode_mapstore_client/client/js/apps/gn-document.js, geonode_mapstore_client/client/js/apps/gn-geostory.js, geonode_mapstore_client/client/js/apps/gn-map.js, geonode_mapstore_client/client/js/plugins/index.js
This storeDetailsInfoDashboardEpic introduced in latest version of mapstore should not be used by geonode because includes actions related to geostore the default MapStore backend.
This PR removes storeDetailsInfoDashboardEpic from the epic included in geonode because it's adding a not needed  request
=> [Backport 4.3.x] Fix #Request to rest/geostore in latest version when loading dashboard (#1814)

geonode_mapstore_client/client/js/routes/Viewer.jsx, geonode_mapstore_client/client/js/utils/ResourceUtils.js
This PR improve the Viewer route checks to allows resource update for the same resource_type
=> [Backport 4.3.x] Fix #1811 Dataset viewer breaks when clicking a linked dataset (#1816)

geonode_mapstore_client/client/js/api/geonode/user/index.js, geonode_mapstore_client/client/js/routes/Viewer.jsx
This PR fixes the primary key comparison in the Viewer component that was causing the infinite loading of dataset
=> [Backport 4.3.x] Fix #1827 Infinite loading for dataset embed (#1828)

geonode_mapstore_client/client/js/epics/gnresource.js
The updates introduced in #1819 were missing the refactor of map viewer linked resources property.
The map workflow was still using the parsed linked resources instead the resources one (the difference is in the variable case style)
=> Fix #1818 Missing connection between map and viewer

geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx, geonode_mapstore_client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/templates/geonode-mapstore-client/_geonode_config.html
This PR remove the filter `filter{subtype.in}=remote` in favor of `filter{sourcetype.in}=REMOTE`. This new filter has been included also in the documents page
=> Fix #1813 Use sourcetpye instead of subtype for filtering remote resources

geonode_mapstore_client/apps.py, geonode_mapstore_client/client/js/components/DetailsPanel/DetailsAssets.jsx, geonode_mapstore_client/client/js/components/DetailsPanel/DetailsInfo.jsx, geonode_mapstore_client/client/js/components/DetailsPanel/DetailsLinkedResources.jsx, geonode_mapstore_client/client/js/components/DetailsPanel/DetailsManagement.jsx, geonode_mapstore_client/client/js/components/DetailsPanel/DetailsPanel.jsx, geonode_mapstore_client/client/js/epics/gnsave.js, geonode_mapstore_client/client/js/plugins/DetailViewer.jsx, geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx, geonode_mapstore_client/client/js/plugins/detailviewer/tabComponents.js, geonode_mapstore_client/client/js/selectors/resource.js, geonode_mapstore_client/client/js/utils/PluginsContextUtils.js, geonode_mapstore_client/client/js/utils/ResourceUtils.js, geonode_mapstore_client/client/themes/geonode/less/_details-panel.less, geonode_mapstore_client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json, geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json, geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json, geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
This PR adds a new tab called **Management** inside the resource panel with the following checkboxes:
- Preserve uploaded metadata
- Approved
- Published
- Featured
- Advertised
Once one of the above checkbox is changes a user need to save the resource to persist the change
=> Fix #1847 Implement the client UI for the Resource management settings

geonode_mapstore_client/client/js/epics/gnresource.js
This PR includes a check to prevent the map viewer request if a config query paramenter is defined in the location
=> Fix #1855 The preview for maps shouldn't show the viewer plugins

geonode_mapstore_client/client/js/epics/gnsave.js
This PR includes refresh the content of the resource with the payload returned by the save workflow
=> Fix #1857 After saving a resource the resource information must be refreshed

geonode_mapstore_client/client/js/components/CardGrid/CardGrid.jsx, geonode_mapstore_client/client/js/components/FeaturedList/Cards.jsx, geonode_mapstore_client/client/js/components/FeaturedList/FeaturedList.jsx, geonode_mapstore_client/client/js/components/FiltersMenu/FiltersMenu.jsx, geonode_mapstore_client/client/js/epics/gnresource.js, geonode_mapstore_client/client/js/plugins/ResourcesGrid.jsx, geonode_mapstore_client/client/js/utils/ResourceUtils.js, geonode_mapstore_client/client/themes/geonode/less/_card-grid.less, geonode_mapstore_client/client/themes/geonode/less/_menu.less, geonode_mapstore_client/templates/documents/document_embed.html, geonode_mapstore_client/templates/geonode-mapstore-client/catalogue.html, geonode_mapstore_client/templates/geonode-mapstore-client/dashboard_embed.html, geonode_mapstore_client/templates/geonode-mapstore-client/dataset_embed.html, geonode_mapstore_client/templates/geonode-mapstore-client/geostory_embed.html, geonode_mapstore_client/templates/geonode-mapstore-client/map_embed.html, geonode_mapstore_client/templates/geonode-mapstore-client/snippets/head.html, geonode_mapstore_client/templates/geonode-mapstore-client/snippets/menu_item.html, geonode_mapstore_client/templates/geonode-mapstore-client/snippets/resource_card.html, geonode_mapstore_client/templates/geonode-mapstore-client/snippets/resources_grid.html, geonode_mapstore_client/templates/index.html, geonode_mapstore_client/templates/page.html
This PR introduces following updates:
- centralize head tags in a new snippet (head.html) to override favicon or fonts
- introduction of two new snippets reasource_card.html and resources_grid.html to replicate the resource grid in django templates
- remove all the js logic to resize resources grid card in favor of [CSS container queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries). This simplify the js code and align styles between react and django templates
- include the possibility to move order button of the resource grid to the left
- featured resources in homepage will show always four cards following the same layout of resources grid
- update the authentication redirect including also the hash path when available
=> Updates to improve templates customizations

geonode_mapstore_client/templates/geonode-mapstore-client/snippets/resources_grid.html
This PR fixes the message `Resource found` in `Resources found` when count is different from 1
=> Fix resources grid count message

geonode_mapstore_client/client/js/apps/gn-dashboard.js, geonode_mapstore_client/client/js/apps/gn-document.js, geonode_mapstore_client/client/js/apps/gn-geostory.js, geonode_mapstore_client/client/js/apps/gn-map.js, geonode_mapstore_client/client/js/components/Menu/MenuItem.js, geonode_mapstore_client/client/js/plugins/ActionNavbar.jsx, geonode_mapstore_client/client/js/plugins/Share.jsx, geonode_mapstore_client/client/js/plugins/actionnavbar/buttons.jsx, geonode_mapstore_client/client/js/plugins/share/ShareEmbedLink.jsx, geonode_mapstore_client/client/js/plugins/share/SharePageLink.jsx, geonode_mapstore_client/client/js/routes/MapViewer.jsx, geonode_mapstore_client/client/js/utils/AppUtils.js, geonode_mapstore_client/client/js/utils/__tests__/AppUtils-test.js, geonode_mapstore_client/client/themes/geonode/less/_share.less, geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json, geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json, geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json, geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
This PR improves the share embed section to include the fullscreen plugin, the embed share link has been converted from url to iframe snippet.
Now when an embed page uses the `allowFullscreen=true` query param the fullscreen button will be added in a menu to the bottom of the iframe.
In the screenshot on the left embed whithout fullscreen and on the right with fullscreen
New embed section in share panel
=> Fix #1879 Include fullscreen button in embed pages

geonode_mapstore_client/client/js/apps/gn-dashboard.js, geonode_mapstore_client/client/js/apps/gn-document.js, geonode_mapstore_client/client/js/apps/gn-geostory.js, geonode_mapstore_client/client/js/apps/gn-map.js, geonode_mapstore_client/client/js/components/Menu/MenuItem.js, geonode_mapstore_client/client/js/plugins/ActionNavbar.jsx, geonode_mapstore_client/client/js/plugins/Share.jsx, geonode_mapstore_client/client/js/plugins/actionnavbar/buttons.jsx, geonode_mapstore_client/client/js/plugins/share/ShareEmbedLink.jsx, geonode_mapstore_client/client/js/plugins/share/SharePageLink.jsx, geonode_mapstore_client/client/js/routes/MapViewer.jsx, geonode_mapstore_client/client/js/utils/AppUtils.js, geonode_mapstore_client/client/js/utils/__tests__/AppUtils-test.js, geonode_mapstore_client/client/themes/geonode/less/_share.less, geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json, geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json, geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json, geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
This PR improves the share embed section to include the fullscreen plugin, the embed share link has been converted from url to iframe snippet.
Now when an embed page uses the `allowFullscreen=true` query param the fullscreen button will be added in a menu to the bottom of the iframe.
In the screenshot on the left embed whithout fullscreen and on the right with fullscreen
New embed section in share panel
=> [Backport 4.4.x] Fix #1879 Include fullscreen button in embed pages (#1880)

geonode_mapstore_client/client/js/plugins/Operation/components/UploadPanel.jsx, geonode_mapstore_client/client/js/plugins/Operation/index.jsx, geonode_mapstore_client/client/js/routes/UploadDataset.jsx, geonode_mapstore_client/client/js/utils/UploadUtils.js, geonode_mapstore_client/static/mapstore/configs/localConfig.json
This PR align the upload configuration to changes introduced in https://github.com/GeoNode/geonode/pull/12673
=> Review operations configurations

geonode_mapstore_client/client/js/components/Autocomplete/Autocomplete.jsx, geonode_mapstore_client/client/js/components/SelectInfiniteScroll/SelectInfiniteScroll.jsx, geonode_mapstore_client/client/js/plugins/MetadataEditor/components/_fields/SchemaField.jsx, geonode_mapstore_client/client/js/plugins/MetadataEditor/components/_templates/DescriptionFieldTemplate.jsx, geonode_mapstore_client/client/js/plugins/MetadataEditor/components/_templates/TitleFieldTemplate.jsx, geonode_mapstore_client/client/js/plugins/MetadataEditor/components/_templates/index.js, geonode_mapstore_client/client/themes/geonode/less/_metadata.less
This PR improves the following
- Enhances autocomplete to allow creation of new entries based on the schema with property `creatable`
- Adds title field with help interactive icon
=> Autocomplete with create entries & metadata title field with help interactive icon

geonode_mapstore_client/client/js/components/Autocomplete/Autocomplete.jsx, geonode_mapstore_client/client/js/components/SelectInfiniteScroll/SelectInfiniteScroll.jsx, geonode_mapstore_client/client/js/plugins/MetadataEditor/components/_fields/SchemaField.jsx
This PR enhances following aspects of the autocomplete 
- Handle additional schema type for autocomplete (enhancement)
- Handle duplicate entry creation in autocomplete (fix)
=> Autocomplete enhancement with additional schema types

geonode_mapstore_client/client/js/components/Autocomplete/Autocomplete.jsx, geonode_mapstore_client/client/js/plugins/MetadataEditor/components/_fields/SchemaField.jsx, geonode_mapstore_client/client/themes/geonode/less/_metadata.less
This PR handles display of error message in autocomplete fields
=> Fix - Autocomplete field not showing validation error

geonode_mapstore_client/client/js/plugins/MetadataEditor/containers/MetadataUpdateButton.jsx
This PR handles the extra error in failure response
=> Handle extra error when returned in the failure response

geonode_mapstore_client/client/js/plugins/Print/Author.jsx, geonode_mapstore_client/client/js/plugins/Print/Copyright.jsx, geonode_mapstore_client/client/js/plugins/index.js, geonode_mapstore_client/client/themes/geonode/less/ms-theme.less, geonode_mapstore_client/static/mapstore/configs/localConfig.json, geonode_mapstore_client/static/mapstore/configs/pluginsConfig.json, geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json, geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json, geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json, geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
This PR adds new print plugin components (Author and Copyright) and update configs
- #1908 
> [!NOTE]
Related config.yaml PR is here https://github.com/GeoNode/geoserver-geonode-ext/pull/191
=> #1908: Update print plugins and configurations

geonode_mapstore_client/static/mapstore/configs/pluginsConfig.json
This PR removes allowedRoles props from default config in the CRSSelector plugin (context)
- #1941
=> #1941: Remove allowedRoles constraints from CRSSelector config

geonode_mapstore_client/client/js/plugins/MetadataEditor/components/_templates/ObjectFieldTemplate.jsx, geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json, geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json, geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json, geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
This PR adds translations to metadata's fallback group title
=> Metadata fallback group title translation added

geonode_mapstore_client/static/mapstore/configs/localConfig.json
This PR fixes the layer settings component used for internal layers
- #1937
=> #1937: Fix layers settings for internal layers

geonode_mapstore_client/client/themes/geonode/less/_details-panel.less
This PR addresses issue [#1854.](https://github.com/GeoNode/geonode-mapstore-client/issues/1854) 
My best guess is that there is a difference between Firefox and Chrome in how they handle linebreaking for inline elements that have white-space: nowrap property. 
Apparantly Chrome allows line breaks between inline elements within a container if the container's width is insufficient to accommodate them on a single line, while Firefox renders it differently and no linebreak occurs with that same property value. If the nowrap value is removed, behaviour would be consistent across those two browsers and wrapping happens. 
However, I think this property serves a purpose, it was introduced in [this fix](https://github.com/GeoNode/geonode-mapstore-client/pull/1515) for [this …
=> Fixes #1854 (no linebreak in Firefox)

geonode_mapstore_client/client/js/components/MediaViewer/Media.jsx, geonode_mapstore_client/client/js/components/MediaViewer/SpreadsheetViewer.jsx, geonode_mapstore_client/client/js/utils/FileUtils.js, geonode_mapstore_client/client/js/utils/__tests__/FileUtils-test.js, geonode_mapstore_client/client/package.json, geonode_mapstore_client/client/themes/geonode/less/_media-viewer.less, geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json, geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json, geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json, geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
This PR implements the spreadsheet document viewer (`csv`, `xls`, `xlsx`)
- #1949
=> #1949: Implement spreadsheet document viewer

geonode_mapstore_client/templates/geonode-mapstore-client/snippets/topbar.html, geonode_mapstore_client/templatetags/get_menu_json.py
This PR created according to the issue #1988 
Regarding the user menu new options, when the user is an admin user the result is the following:
while when the user is a simple authenticated user the result is the following:
=> [ISSUE 1988] moving the About menu to the user menu

geonode_mapstore_client/client/js/api/geonode/v2/metadata.js, geonode_mapstore_client/client/js/plugins/MetadataEditor/components/_fields/SchemaField.jsx, geonode_mapstore_client/client/js/plugins/MetadataEditor/components/_fields/useSchemaReference.js, geonode_mapstore_client/client/js/plugins/MetadataEditor/containers/MetadataEditor.jsx
This PR adds supported for nested dropdown with schema reference in metadata editor
- #1992 
```json
{
"test_sites": {
"type": "array",
"title": "Test nested schema",
"minItems": 1,
"items": {
"type": "object",
"properties": {
"site": {
"title": "site",
"type": "object",
"properties": {
"id": {
"type": "string"
},
"label": {
"type": "string"
}
},
"ui:options": {
"geonode-ui:autocomplete": "/api/v2/metadata/autocomplete/categories"
}
},
"locations": {
"title": "locations",
"type": "array",
"minItems": 1,
"items": {
"type": "object",
"title": "test_location",
"properties": {
"id": {
"type": "string"
},
"label": {
"type": "string"
}
},
"ui:options": {
"geonode-ui:referencevalue": "test_sites.[${index}].site.id",
"geoode-ui:referencekey": "id",
"geonode-ui:autocomplete": …
```
=> #1992: Metadata editor: 2-levels nested dropdown support

geonode_mapstore_client/client/js/epics/__tests__/gnsave-test.js, geonode_mapstore_client/client/js/epics/index.js
This PR restricts the dataset API calls for perms to layers from geonode catalog
- #1986
=> #1986: Restrict dataset API calls to layers from GeoNode’s catalog

geonode_mapstore_client/client/js/apps/gn-catalogue.js, geonode_mapstore_client/client/js/plugins/Operation/components/ExecutionRequestTable.jsx, geonode_mapstore_client/client/js/plugins/UploadOperation.jsx, geonode_mapstore_client/client/js/plugins/UploadResource.jsx, geonode_mapstore_client/client/js/plugins/index.js, geonode_mapstore_client/client/js/routes/UploadDataset.jsx, geonode_mapstore_client/client/js/routes/UploadDocument.jsx, geonode_mapstore_client/client/themes/geonode/less/_upload.less, geonode_mapstore_client/static/mapstore/configs/localConfig.json
This PR allow possibility to configure action button after upload of the resource is complete. By default only `View` resource button is visible
- #1979
=> #1979 - Allow to edit metadata after resource creation

geonode_mapstore_client/client/js/epics/gndownload.js, geonode_mapstore_client/client/themes/geonode/less/_menu.less
This PR fixes the metadata downloads files are broken when filename has dot it in treating the content after dot as extension resulting in a generic file. After this fix, files are downloaded correctly with the proper extension, even when filenames contain multiple dots or spaces
- #2000
=> #2000: Fix - Metadata download filenames broken

geonode_mapstore_client/client/js/plugins/Operation/components/ExecutionRequestTable.jsx, geonode_mapstore_client/client/js/plugins/UploadResource.jsx, geonode_mapstore_client/static/mapstore/gn-translations/data.de-DE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.en-US.json, geonode_mapstore_client/static/mapstore/gn-translations/data.es-ES.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fi-FI.json, geonode_mapstore_client/static/mapstore/gn-translations/data.fr-FR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.hr-HR.json, geonode_mapstore_client/static/mapstore/gn-translations/data.it-IT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.nl-NL.json, geonode_mapstore_client/static/mapstore/gn-translations/data.pt-PT.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sk-SK.json, geonode_mapstore_client/static/mapstore/gn-translations/data.sv-SE.json, geonode_mapstore_client/static/mapstore/gn-translations/data.vi-VN.json, geonode_mapstore_client/static/mapstore/gn-translations/data.zh-ZH.json
This PR adds possibility to configure label for the upload operation action buttons. when `editMetadata: true` , by default the label is `Fill Metadata`
- #2006
=> #2006: Allow label configuration of upload operation action buttons

geonode_mapstore_client/client/js/plugins/actionnavbar/buttons.jsx
Improve visibility control of filter button in dataset pages. Now the filter button is visible only for layer with the search parameter (WFS)
=> Fix #2027 Filter button for Datasets should be active only if the WFS link is available

geonode_mapstore_client/client/js/plugins/ActionNavbar/index.jsx, geonode_mapstore_client/client/js/plugins/Save.jsx, geonode_mapstore_client/client/js/plugins/SaveAs.jsx, geonode_mapstore_client/client/themes/geonode/less/_action-navbar.less, geonode_mapstore_client/client/themes/geonode/less/_brand-navbar.less, geonode_mapstore_client/client/themes/geonode/less/geonode.less
> [!NOTE]
Supporting PR to add menu divider style on MS is [here](https://github.com/geosolutions-it/MapStore2/pull/10997)
=> Fix - ActionNavbar style

geonode_mapstore_client/templatetags/get_menu_json.py
This PR was created according to this issue: #2052 
The issue came from a typo in the `Favorites` URL search in the `get_menu_json.py` file.
=> Fixing Favorites URL in the user menu

geonode_mapstore_client/client/js/components/MediaViewer/__tests__/Media-test.jsx, geonode_mapstore_client/client/js/components/MetadataPreview/MetadataPreview.jsx, geonode_mapstore_client/client/themes/geonode/less/_action-navbar.less, geonode_mapstore_client/client/themes/geonode/less/_footer.less, geonode_mapstore_client/client/themes/geonode/less/_main-event.less
This PR fixes the menu items hidden in viewer
=> Fix - Actionbar menus are hidden behind the document viewer

geonode_mapstore_client/client/js/epics/gnresource.js, geonode_mapstore_client/client/js/plugins/save/withPrompt.jsx
This PR addresses the issue where pending changes were retained when navigating away from the page causing unwanted side effects
=> Reset pending changes on viewer page change

geonode_mapstore_client/client/js/epics/gnsave.js
This PR fixes a resource update error that occurred when editing permissions. The issue was likely caused by asynchronous permission handling interfering with the resource update process, resulting in a 404 error. The fix ensures that permissions are updated after the resource has been successfully updated
=> Fix - Prevent update error when editing permission

geonode_mapstore_client/client/js/plugins/ResourceDetails/ResourceDetails.jsx
This PR fixes the persistence of resource card highlight even upon detail panel is closed
- #2098
=> Remove resource card selection upon detail panel close

geonode_mapstore_client/client/package.json
This PR adds a new script to `package.json` to support hybrid builds using the `MAPSTORE_COMPILE_DEV=true` flag now supported by `mapstore-project`. See geosolutions-it/mapstore-project#27 in the mapstore-project repository for details on this.
**Changes:**
Adds a new NPM script:
```json
"compile:dev": "MAPSTORE_COMPILE_DEV=true mapstore-project compile && node postCompile"
```
This allows the MapStore client to be built with:
- Source maps
- Development Webpack mode
- All production assets (themes, translations, configs)
**Why:**
This is useful for deploying builds to staging/QA environments where full production content is needed but debugging (e.g., via browser DevTools and source maps) is still required.
**Example usage:**
```sh
npm run compile:dev
```
This will produce a fully …
=> [Fixes #2055] Add compile:dev script using MAPSTORE_COMPILE_DEV=true for debug-friendly production builds
